////
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see https://www.gnu.org/licenses/.
////

= DragonHack
Sean-Patrick Ortencio Clayton
v1: PRE-ALPHA DRAFT
:doctype: book
:!showtitle:
:!table-caption:
:showcommentary:
:icons: font
:stylesheet: styles.css
:sectanchors:
:version-label: Edition
:toc: right
:toclevels: 4
:imagesdir: images
:favicon: images/dragonhack-logo.svg
:repo-url: https://github.com/sean-clayton/dragonhack

image::dragonhack-logotype.svg[Static,480,id=logo,alt=DragonHack,link=#]

<<<

[preface]
== Preface

{doctitle} is inspired by several games.
Here is a non-exhaustive list in alphabetical order:

* https://www.bladesinthedark.com[Blades in the Dark] by John Harper.
* https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel.
* https://freeleaguepublishing.com/en/games/forbidden-lands/[Forbidden Lands] by the workers at Fria Ligan.
* https://www.ironswornrpg.com/[Ironsworn] by Shawn Tomkin.
* https://www.drivethrurpg.com/product/250888/Knave[Knave] by Ben Milton.
* The Streets of Marienburg.
* https://johnharper.itch.io/world-of-dungeons[World of Dungeons] by John Harper.
* ... and the many games derived from those.

If you enjoy {doctitle}, then be sure to check out these other games!

<<<

== Rules

=== Playing {doctitle}

To play {doctitle}, you create your character, make some decisions about the world you inhabit, and set the story in motion.
When you encounter something dangerous or otherwise act by taking risks, your choices and the dice determine the outcome.

{doctitle} supports three modes of play.

Guided::
  One or more players take the role of their characters, the protagonists in your story, while a group mediator/gamemaster (GM) moderates the session.
  The GM helps bring the world to life, portrays the people and creatures you encounter, and makes decisions about the outcome of your actions.
Cooperative (Co-Op)::
  You and one or more friends play together to overcome challenges and complete quests.
  A GM is not required.
  The {doctitle} game system will help you explore the dramatic stories of your characters and their fateful vows.
Solo::
  As with cooperative play, no GM is necessary.
  You portray a lone heroic character in a dangerous world.
  Good luck!

[sidebar]
--
{doctitle} is primarily intended for small group play or solo.
One to four players (plus a GM in guided mode) is ideal.
--

==== What You Need to Play

{doctitle} requires some materials. Here is what you'll need:

* Several six-sided dice for each player.
  Five at the least, but more cannot hurt.
  These are used for [term]#action dice#, [term]#oracle dice#, and rolling things like [term]#damage#.
* A character sheet for each player.

==== Mechanics and the Fiction

{doctitle} uses various mechanics, such as rolling dice and managing the stats and resources on your character sheet.
As a player, you will often make decisions based on a desired mechanical outcome.
For example, you might choose a particular action to get a bonus or advantage on your die roll.
The basic mechanics of {doctitle} are introduced in this chapter.

{doctitle} is also heavily reliant on the fiction, which is the imagined characters, situations, and places within your game.
You will play from the perspective of your character.
You will interpret actions and events in a way that is consistent with the dramatic, fictional reality you have forged for your story and your world.

==== Your Character

You use your character sheet to track your stats, gear, and overall condition.

However, your character is more than these mechanical bits.
You are a character in a rich story.
You have hopes and fears, virtues and failings.
You have a history.
You are, or were, part of a community.
This is the fiction of your character.
Consider a few of these details as you create your character, but don't sweat it -- you'll evolve it through play.
At the start of your game, put your character on stage to see what happens. 
Fill in the blanks -- for your character and your world -- as you go.

=== Rolling Dice

The only dice used in {doctitle} are six-sided dice.

When we roll multiple dice, we shorten it to just the number of dice followed by a D, eg: Rolling two dice is 2D, and rolling 1 dice is 1D.

Sometimes you add or subtract a number to the total of the dice.
This has a + or - after the dice along with the number that is to be added or subtracted, respectively.
For example, if we want to add 1 to the total of a 2D roll, it looks like 2D+1.
If we want to subtract 1 from the total of a 2D roll, it looks like 2D-1.

Sometimes we want to roll multiple dice and not add them together, but take the best or worst of the dice rolled.
This is written as b[ ] or w[ ] with the number of dice in between the brackets.
For example, if we want to roll 2D and keep only the best of the two, it looks like b[2D].
If we want to roll 2D and keep only the worst of the two, it looks like w[2D].

We can also take multiple of the best or multiple of the worst.
This looks like the previous form, but with a number after the b or w, before the brackets.
For example, if we want to roll 3D and take the best two, it looks like b2[3D].
If we want to roll 3D and take the worst two, it looks like w2[3D].

And like rolling dice normally, we can still add a number to the total to these best of/worst of forms.
For example, b2[3D]+4 adds 4 to the total of the best two dice of the three rolled.
w2[3D]-1 subtracts 1 from the total of the worst two dice of the three rolled.

==== Other Dice Roll Notation

[horizontal]
d3::
  Roll a dice.
  *1/2* = 1.
  *3/4* = 2.
  *5/6* = 3.
d66::
  Roll a dice twice.
  The first roll is the tens place and the second is the ones.
d666::
  Roll like a d66, but with another roll for the hundreds place.
d33::
  Like a d66, but each digit is a d3.
d333::
  Like a d33, but with another roll for the hundreds place.

=== Rounding

In {doctitle}, always round down when faced with non-integer numbers, unless otherwise noted.

=== The Challenge Roll

The core mechanic in {doctitle} is the challenge roll.
To perform a challenge roll, you roll multiple dice at once and read the *single highest result*.
The most dice you can roll in a challenge roll is 5.

To create a dice pool for a challenge roll, you use an attribute or other number, called a [term]#stat#, and roll an amount of dice equal to its rating.
For example, if you roll with the [term]#heart# attribute and its value is 3, this is written as "Roll [term]#+heart#" and you would add 3 to your dice pool.

[sidebar]
If you ever need to roll but you have zero (or negative) dice, roll two dice and take the single lowest result.
You can’t roll a critical when you have zero dice.

The total of your action dice, your stat, and any additional bonuses is your action score.

There are five possible results of a challenge roll:

[horizontal]
Critical Hit::
  You roll *more than one 6*.
Strong Hit::
  The highest die is a *6*.
Weak Hit::
  The highest die is a *4 or 5*.
Miss::
  The highest die is a *1, 2, or 3*.

There are four types of rolls that you'll use most often in the game:

Taking action::
  When a PC attempts an action that's dangerous or troublesome, you take an action to find out how it goes.
  Taking action and the resulting effects and consequences drive most of the game.
Fortune roll::
  The GM can make a fortune roll to disclaim decision making and leave something up to chance.
  How loyal is an NPC?
  How much does the plague spread?
  How much evidence is burned before the constables kick in the door?
Resistance roll::
  A player can make a resistance roll when their character suffers a consequence they don't like.
  The roll tells us how much stress their character suffers to reduce the severity of a consequence.

==== Surge Points

When you land a [term]#critical hit#, take the lowest number on the dice you rolled, multiply it by 2 and that's your [term]#surge points# for that action.

For example, if you roll 3D and get 3, 6, and 6, the lowest number you rolled was a 3.
We multiply that by two to get the surge points available to you: 6.

You use surge points through moves and features of your <<_paths,[term]#paths#>>.

Any surge points you do not use, you do not maintain.
Use them or lose them during the move.the ones.

==== GMs and the Dice

If you are playing as a GM, you can focus on guiding the game and responding to your player's questions and actions.
NPCs don't need to roll dice when they act, however, you might want some dice available for oracle rolls.

=== Taking Action

When a player character does something challenging, we [term]#take action# to see how it turns out.
An action is challenging if there's an obstacle to the PC's goal that's dangerous or troublesome in some way.
We don't make an action roll unless the PC is put to the test.
If their action is something that we'd expect them to simply accomplish, then we let them accomplish it without making any rolls.

==== Risk

There are three levels of risk.

Minor Risk::
  Something bad could happen, but not very likely.
  Failure is not something to really worry about.
Moderate Risk::
  There's danger here if any failure were to occur.
Major Risk::
  If things go bad, they will go _very_ bad.
  Success here is absolutely paramount.

==== Reward

There are three levels of reward.

Minor Reward::
  You achieve something, but not nearly as much as you'd like.
  If you were stabbing something, it's technically stabbed, but not as much as you'd hope.
  If you were avoiding a danger, you technically avoid it, but you wish you did more.
Moderate Reward::
  You achieve a satisfactory outcome.
  If you were stabbing something, it's stabbed.
  If you were avoiding a danger, it was avoided.
Major Reward::
  You achieve much more than you had expected.
  If you were stabbing something, it sinks in like a hot knife through melted butter.
  If you were avoiding a danger, it is completely avoided, and probably is no longer dangerous for a time.

State what your goal is and the approach your character will take to make it happen.
You choose the <<_abilities,[term]#ability#>> you are using to act out your approach.
The GM will tell you the following:

* The [term]#attribute# you will use.
* The level of [term]#risk# the approach takes.
* The level of [term]#reward# given if the approach succeeds.
* Possible consequences if you fail and if you succeed.

.Take Action
[action]
--
[.lead]
When your character acts by taking a risk, state what your goal is and the approach your character will take to make it happen...

Roll [term]#+attribute#.

[.risk]
Minor Risk::
+
[.lead]
You act on your terms. You exploit a dominant advantage.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  Things go as planned and all is well. A success.
* **Weak Hit:**
  Your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
* **Miss:**
  Your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.

Moderate Risk::
+
[.lead]
You go head to head. You act under fire. You take a chance.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  A success, and you realize what was at stake.
* **Weak Hit:**
  Overall a success, but you must [term]#suffer the consequences#.
* **Miss:**
  Things do not go your way.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences#.

Major Risk::
+
[.lead]
You overreach your capabilities. You're in serious trouble.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  A success, narrowly avoiding the consequences.
* **Weak Hit:**
  Technically a success, but there is a severe cost.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
* **Miss:**
  The worst outcome has happened.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
--

=== Fortune Roll

The fortune roll is a tool the GM can use to disclaim decision making.
You use a fortune roll in two different ways:

. **When you need to make a determination about a situation the PCs aren't directly involved in** and don't want to simply decide the outcome.
. **When an outcome is uncertain**, but no other roll applies to the situation at hand.

When you make a fortune roll you may assess [term]#any attribute or other stat# to determine the stat of the roll, and then perform a regular [term]#challenge roll#.

If no stat applies, roll [term]#+0# for sheer luck or roll [term]#+1–3# based on the situation at hand.

Sometimes you are forced to make a fortune roll.
This can be with a specific attribute or stat, or with a number added.
For example, making a fortune roll with heart, if its value is 3, it is written as "Roll [term]#fortune +heart#" and you would add 3 to the action die.
Making a fortune roll with +2 is written as "Roll [term]#fortune +2#" and you would add 2 to the action die.

.Fortune Roll
[action]
--
* *1D* for each [term]#stat# rating.
* *+1D* for each [term]#major advantage#.
* *-1D* for each [term]#major disadvantage#.

* **Critical Hit**: Exceptional result / Major, extreme reward.
* **Hit**: Good result / Moderate,  full reward.
* **Partial Hit**: Mixed result / Minor, partial reward.
* **Miss**: Bad result / Poor, little reward.
--

=== Surveying

.Surveying
[action]
--
When you search an area, ask questions, conduct an investigation, or follow a track, [term]#roll fortune +wits#.
If you act within a community or ask questions of a person with whom you share a bond, add +1.

* **Major**:
  You get exceptional details.
  The information is complete and follow-up questions may expand into related areas or reveal more than you hoped for.
* **Moderate**:
  You get good details.
  Clarifying and follow-up questions are possible.
* **Minor**:
  You get incomplete or partial information.
  More information gathering will be needed to get all the answers.
--

=== Resistance

After seeing the roll result when [term]#taking action#, you can choose to [term]#resist# the consequences.
The GM will tell you which [term]#attribute# you will use.
You determine what [term]#ability# you use.

ifdef::showcommentary[]
.Regarding rolling resist...
[NOTE]
These could be done much better.
I don't know if I want every stat in play here.
Maybe as monsters are made and more kinds of damage are revealed in the game, they'll make this clearer to handle.
endif::[]

.Resist
[action]
--
[.lead]
When your character resists the consequences of their actions...

Roll [term]#+force# if resisting physical consequences through fortitude and endurance,
[term]#+edge# if resisting physical consequences through quickness or precision,
[term]#+shadow# if resisting detection or discovery through stealth or deception,
[term]#+heart# if resisting emotional damage,
or [term]#+mind#, if resisting trickery, cunning, being deceived, or mental damage.

Add dice according to the [term]#ability# used.

[horizontal]
* **Critical Hit:**
  You avoid all consequences and you are now in control of the situation.
  Gain [term]#1 exertion#.
* **Hit:**
  The consequence is avoided.
* **Weak Hit:**
  The consequence is reduced.
  If taking damage, take half damage.
  You can [term]#mark 1 exertion# to avoid it completely.
* **Miss:**
  The consequence still happens.
  You can [term]#mark 1 exertion# to avoid reduce (half damage if taking damage) it or [term]#mark 2 exertion# to avoid it completely.
--

==== Death

When your character reaches 0HP, they are most likely dead.

After fighting is over and your allies roll you over within a few hours of you reaching 0HP, make a fortune roll [term]#+heart# or [term]#+force#, whichever is higher.
*On a critical hit*, you strongly gasp as they turn you over and you must explain to everyone how it wasn't as bad as it looked.
You regain +HD HP (minimum 1).
*On a strong hit*, you are barely breathing and are in dire need of aid.
You regain 1HP and your exertion is set to max.
*On a weak hit*, you are alive just enough to say some last words.
*On a miss*, you are dead.

=== Progress Tracks

A progress track is a multi-segment track.
Draw a progress track when you need to track ongoing effort against an obstacle or the approach of impending trouble.

Sneaking into the constables watch tower?
Make a progress track to track the alert level of the patrolling guards.
When the PCs suffer consequences from partial successes or missed rolls, fill in segments on the progress track until the alarm is raised.

Generally, the more complex the problem, the more segments in the progress track.

A complex obstacle is a 4-segment track.
A more complicated obstacle is a 6-segment track.
A daunting obstacle is an 8-segment track.

When you create a progress track, make it about the obstacle, not the method.
The progress tracks for an infiltration should be "`Interior Patrols`" and "`The Tower,`" not "`Sneak Past the Guards`" or "`Climb the Tower.`" The patrols and the tower are the obstacles -- the PCs can attempt to overcome them in a variety of ways.

Remember that a progress track tracks progress.
It reflects the fictional situation, so the group can gauge how they're doing.
A progress track is like a speedometer in a car.
It shows the speed of the vehicle -- it doesn't determine the speed.

==== Simple Obstacles

Not every situation and obstacle requires a progress track.
Use progress tracks when a situation is complex or layered and you need to track something over time -- otherwise, resolve the result of an action with a single roll.

Examples of progress tracks follow.

==== Danger Tracks

The GM can use a progress track to represent a progressive danger, like suspicion growing during a seduction, the proximity of pursuers in a chase, or the alert level of roaming monsters in a dungeon.
In this case, when a complication occurs, the GM ticks one, two, or three segments on the progress track, depending on the consequence level.
When the progress track is full, the danger comes to fruition -- the guards hunt down the intruders, activate an alarm, release the hounds, etc.

==== Racing Tracks

Create two opposed progress tracks to represent a race.
The PCs might have a progress track called "`Escape`" while the city watch have a progress track called "`Cornered.`" If the PCs finish their progress track before the watch fill theirs, they get away.
Otherwise, they're cornered and can't flee.
If both complete at the same time, the PCs escape to a safe location, but the watch are right outside!

You can also use racing progress tracks for an environmental hazard.
Maybe the PCs are trying to complete the "`Search`" progress track to find the lockbox on the sinking ship before the GM fills the "`Sunk`" progress track and the vessel goes down.

==== Linked Tracks

You can make a progress track that unlocks another progress track once it's filled.
For example, the GM might make a linked progress track called "`Trapped`" after an "`Alert`" progress track fills up.
As always, the method of action is up to the players and the details of the fiction at hand.

==== Mission Tracks

The GM can make a progress track for a time-sensitive mission, to represent the window of opportunity you have to complete it.
If the countdown runs out, the mission is scrubbed or changes -- the target escapes, the household wakes up for the day, etc.
Tug-of-war progress tracks

You can make a progress track that can be filled and emptied by events, to represent a back-and-forth situation.
You might make a "`Revolution!`" progress track that indicates when the refugees start to riot over poor treatment.
Some events will tick the progress track up and some will tick it down.
Once it fills, the revolution begins.
A tug-of-war progress track is also perfect for an ongoing turf war between two crews or factions.

==== Long-term Project

Some projects will take a long time.
A basic long-term project (like tinkering up a new feature for a device) is eight segments.
Truly long-term projects (like creating a new designer drug) can be two, three, or even four progress tracks, representing all the phases of development, testing, and final completion.
Add or subtract progress tracks depending on the details of the situation and complexity of the project.

A long-term project is a good catch-all for dealing with any unusual player goal, including things that circumvent or change elements of the mechanics or the setting.

==== Faction progress tracks

Each faction has a long-term goal.
When the PCs have downtime, the GM ticks forward the faction progress tracks that they're interested in.
In this way, the world around the PCs is dynamic and things happen that they're not directly connected to, changing the overall situation in the city and creating new opportunities and challenges.

The PCs may also directly affect NPC faction progress tracks, based on the missions and scores they pull off.
Discuss known faction projects that they might aid or interfere with, and also consider how a PC operation might affect the NPC progress tracks, whether the players intended it or not.

=== The Flow of Play

Like most roleplaying games, you play primarily from the perspective of your character.
What are you doing?
What are you trying to achieve?
What opposition and challenges do you face?
Your quests, and the characters and situations you encounter, will guide the fiction and the choices you make.

When you have questions about what you find, how other characters in your world respond, or what happens next, you can go with what feels right (if you're playing solo or co-op), or ask your GM.
When you are seeking inspiration or want to put it in the hands of fate, you want to consult an <<_oracles, oracle>>.
Use the yes/no questions and random prompts to generate interesting twists and new complications you might not have thought of on your own.
Above all, if it's interesting, dramatic and fits the fiction, make it happen.

If you are doing something covered by a move, refer to the move to resolve your action.
If it tells you to roll dice, do it.

Scoring a strong hit on a move means you are in control.
You're driving the narrative.
What do you do next?

A weak hit or a miss means you don't have control of the situation.
Instead of acting, you react.
What happens next?
If you're playing with a GM, they'll determine how the world responds.
Otherwise, you rely on your intuition and occasional oracle rolls to drive the narrative.

== Character Creation

. *Envision* your character
. Choose a <<_kin,[term]#kin#>> and determine their [term]#age#.
. Set your <<_attributes,[term]#attributes#>> by applying these points across [term]#force#, [term]#edge#, [term]#shadow#, [term]#wits#, and [term]#heart#.
  Do not exceed 2 on any of these.
  * *Young:* 4 points.
  * *Middle-aged:* 3 points.
  * *Old:* 2 points.
. Choose your <<_drive,[term]#drive#>> and <<_vice,[term]#vice#>>.
. Choose your <<_core_paths,[term]#core path#>>, and then your <<_focus_paths,[term]#focus path#>> according to your age.
  * *Young:* No focus paths.
  * *Middle-aged/Old:* 1 focus path. Assume the narrative requirement of that path is in your character's backstory.
. Gain XP according to your age that you can spend now if you wish, or hold for later.
  * *Young:* 8XP.
  * *Middle-aged:* 16XP.
  * *Old:* 24XP.
. Roll your <<_careers,[term]#careers#>>, purchase additional <<_equipment, [term]#equipment#>>, and mark your <<_speed,[term]#speed#>>.
  The career titles you  become [term]#secondary skills#.
  You start with 10c and, in addition, gain all coin and equipment from your careers.
  * *Young:* Roll once on the careers table.
  * *Middle-aged:* Pick one and then roll once on the careers table.
  * *Old:* Pick two and then roll once on the careers table.
. Fill out personal information such as your name and other details.

=== Experience

At the end of a session, have each person at the table go through the following items and, unless otherwise noted, mark 1XP for each one that everyone agrees is true for them.

* XP for showing up to the session.
* XP for acting according to your <<_drive,[term]#drive#>> in a memorable way.
* XP for every 100 &times; HD (minimum 100) coin spent without any in-world gain on your <<_vice,[term]#vice#>> this session.
* XP for killing a monster or otherwise dangerous foe.
* XP for looting a magical artefact.
* XP for discovering a settlement, dangerous site, or otherwise storied.
* XP for you or an ally earning the trust or gratitude of an NPC.
* XP for you or an ally making a new enemy who will now be acting against you.

<<_paths, [term]#Paths#>> also provide ways of gaining XP.
Only characters with those paths can gain XP in those ways.

== Exertion

Exertion represents the amount of effort, physical or mental, you can exert while adventuring.
When you [term]#mark exertion#, you add exertion against your maximum exertion.

When you are at max exertion and you have to [term]#mark exertion#, you're [term]#broken# and can no longer act.
This means you are either physically battered and unconscious, emotionally unavailable, mentally drained, or otherwise completely exhausted.
Regardless, when you are broken you are out of any scene you currently are in and all scenes going forward, and are susceptible to a [term]#coup de grace#, which means all damage done to you is doubled.

You are broken until you somehow regain [term]#exertion#.

== Hit Points and Hit Dice

Every character starts with 6 hit points (HP) and 0 hit dice (HD).
[term]#Hit dice# provide a way of determining your vitality and also boost your HP.
Whenever you gain HD, roll the amount of HD gained in dice and add that to your current HP.
Whenever you re-roll your health, you roll a number of dice equal to your total HD, add 6, and that is your new health.
For example, if you have 2HD, you would roll 2D+6.

Sometimes you can add [term]#HD# to a roll (often with damage).
This is notated as +HD.
This means you roll dice like normal, and then add the amount of [term]#hit dice# you have to the total of the roll.
For example, if you are rolling 1D+HD and you have 2HD, then you are rolling 1D+2.

Sometimes you can roll [term]#HD# and add the result to a roll (often with damage).
This is notated as &times;HD.
This means you roll dice like normal, but also add your number of HD to the dice rolled.
For example, if you are rolling 2D while something grants you &times;HD for that roll and you have 2HD, then you are rolling 4D.

== Abilities

Abilities are general actions that increase your chances of succeeding when [term]#taking action#.
The following are the general abilities in {doctitle}:

* [term]#Aim and Shoot#
* [term]#Care#
* [term]#Charm#
* [term]#Command#
* [term]#Contort#
* [term]#Deceieve#
* [term]#Dodge#
* [term]#Focus#
* [term]#Frighten#
* [term]#Hack and Slash#
* [term]#Lead#
* [term]#Notice#
* [term]#Sneak#
* [term]#Study#
* [term]#Sway#
* [term]#Treat#
* [term]#Wrestle#

Your <<_paths,[term]#paths#>> will determine your primary and secondary abilities.

Abilities, both primary and secondary, _always_ give a bonus to [term]#taking action#.
Primary abilities, though, can provide greater bonuses than secondary abilities.

=== Aim and Shoot

=== Care

=== Charm

=== Command

=== Contort

=== Deceieve

=== Dodge

=== Focus

=== Frighten

=== Hack and Slash

=== Lead

=== Notice

=== Sneak

=== Study

=== Sway

=== Treat

=== Wrestle

== Drive

== Vice

== Kin

=== Human

Human people.

.Age ranges
[horizontal]
Young Adult:: 16–25
Middle-Aged:: 26–59
Old:: 60+

=== Hobbitfolk

Small people.

.Age ranges
[horizontal]
Young Adult:: 20–29
Middle-Aged:: 30–69
Old:: 70+

=== Goblin

Small people with pointy ears.

.Age ranges
[horizontal]
Young Adult:: 11–15
Middle-Aged:: 16–29
Old:: 30+

=== Dwarf

Small people with beards.

.Age ranges
[horizontal]
Young Adult:: 25–100
Middle-Aged:: 101–199
Old:: 200+

=== Vyrmit

Mouse/rat/hamster people.

.Age ranges
[horizontal]
Young Adult:: 11–15
Middle-Aged:: 16–29
Old:: 30+

=== Kolussar

Ancient human/dwarf people.

.Age ranges
[horizontal]
Young Adult:: 40–119
Middle-Aged:: 120–249
Old:: 250+

=== Testadar

Turtle/tortoise people.

.Age ranges
[horizontal]
Young Adult:: 50–150
Middle-Aged:: 151–299
Old:: 300+

=== Kyrfit

Raven/crow/rook people.

.Age ranges
[horizontal]
Young Adult:: 14–20
Middle-Aged:: 21–34
Old:: 35+

== Paths

There are two types of paths: core paths and focus paths.
Your core path is the primary path your character takes.
Focus paths are ways to shape your character into the concept you have in your mind.

Pick the core path for your character.
*If you are middle-aged*, pick a focus path or a move for a core path for free and start with 8XP.
*If you are old*, pick a focus path for free, one [term]#tier I ability#, and start with 8XP.

XP you start with during character creation can be saved for later use.

ifdef::showcommentary[]
.Regarding path power
[NOTE]
Paths are not meant to be a _huge_ power boost to characters.
Magic items are meant to be the biggest power boost a character can get -- they break all the rules and even rewrite them.
Paths are meant to be boosts, yes, but really they should increase versatility of a character.
For example, the Mystic path gets new properties for their spells they cast.
endif::[]

=== Talents

Your paths give you access to talents.
Talents have two key things to note about them: Their [term]#tier# and their XP cost.
You can always access [term]#tier I# talents and can take them as long as you spend their required XP cost.
To gain an ability in [term]#tier II# or above you must have N+2 talents of the previous [term]#tier# where N is the number of talents you already have in the [term]#tier# of the ability you are choosing.
For example, in order to gain your first [term]#tier II# ability, you must have two [term]#tier I# talents.
In order to gain a second [term]#tier III# ability, you must have at least three [term]#tier II# talents which means you must have at least four [term]#tier I# talents.

== Core Paths

ifdef::showcommentary[]
.Regarding core paths
[NOTE]
Core paths are the core chassis of a character.
They are essentially "classes" in other fantasy role-playing games.
endif::[]

There are three core paths: The warrior, the mystic, and the scoundrel.
The warrior knows their weapons and can kill many things with them.
The mystic knows mystery and spells and can kill many things with it.
The scoundrel has tricks, guile, and skulduggery and can kill many things through those.

=== The Warrior

You start with 10 available [term]#exertion#.

Choose one of the three following features:

* *The Fighter:*
  _When you are entering the fray of battle with reckless abandon_, you can [term]#mark exertion# to count as one tier higher in <<_speed,[term]#speed#>> and have [term]#+1 armor# until the fight is over.
* *The Ranger:*
  _When you engage in a fight with something you've been tracking and preying on_, you can [term]#mark exertion# to gain +1D when acting to defeat it.
  This lasts until they escape or they are defeated.
  After which, you can choose a new target to track and make your prey.
* *The Stalwart:*
  _When you are protecting an ally and take damage_, you can [term]#mark exertion# to increase your armor by 1 when [term]#using armor#.
  You can do this as long as you have exertion to mark.

.Warrior Tier I Talents
* *Talent name* - Increase your HD by 1. You can take this up to 2 times.
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Warrior Tier II Talents
* *Talent name* - Increase your HD by 1. You can take this up to 2 times.
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Warrior Tier III Talents
* *Talent name* - Increase your HD by 1. You can take this up to 2 times.
* *Talent name* - Description
* *Talent name* - Description

=== The Mystic

You start with 6 available [term]#exertion#.

You gain access to <<_mysticism, mysticism>>.

.Mystic Tier I Talents
* *Talent name* - Increase your HD by 1.
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Mystic Tier II Talents
* *Talent name* - Increase your HD by 1.
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Mystic Tier III Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

=== The Scoundrel

You start with 8 available [term]#exertion#.

Choose one of the three following features:

* *The Thief:*
  You gain [term]#steal# as a [term]#primary ability#.
* *The Assassin:*
  You gain [term]#slit throat# as a [term]#primary ability#.
* *The Minstrel:*
  _When you perform a song while resting with your party_, any [term]#broken# ally gains w[2D] [term]#exertion# back.

.Scoundrel Tier I Talents
* *Sneak attack* - *Cost* 8XP. When you use [term]#edge# to attack and deal damage to an unaware target with a [term]#small# or [term]#ranged# weapon, roll [term]#HD# to add as damage to your attack.
* *Talent name* - *Cost* 8XP. Increase your HD by 1. You can take this up to 2 times -- the second time you take it costs 10XP.
* *Talent name* - Gain a new [term]#primary ability: Encourage#
* *Talent name* - Gain a new [term]#primary ability: Slit throat#
* *Talent name* - Gain a new [term]#primary ability: Encourage#
* *Talent name* - Make one of your [term]#secondary abilities# become a [term]#primary ability#. You can take this up to 2 times.
* *Talent name* - Gain a new [term]#secondary ability# of your choice. You can take this up to 2 times times.

.Scoundrel Tier II Talents
* *Talent name* - *Cost* 15XP. Increase your HD by 1. You can take this up to 2 times -- the second time you take it costs 20XP.
* *Talent name* - Your primary ability bonus becomes +2. Your secondary ability bonus becomes +1.
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Scoundrel Tier III Talents
* *Talent name* - *Cost* 25XP. Increase your HD by 1. You can take this up to 2 times -- the second time you take it costs 40XP.
* *Talent name* - Description
* *Talent name* - Description

=== The Devoted

You start with 8 available [term]#exertion#.

Choose one of the three following features:

* *The Faithful:*
  You gain [term]#stealth# as a [term]#primary ability#.
* *The Druid:*
  You can add +1 to [term]#heart# instead of [term]#shadow# or [term]#edge#.
  You gain [term]#lead# as a [term]#primary ability#.

== Focus Paths

ifdef::showcommentary[]
.Regarding focus paths
[NOTE]
Focus paths are the way to _really_ flesh out a character concept.
Focus paths are a _great_ place to add homebrew content.
These are like "subclasses" in other fantasy role-playing games.
The goal of a focus path is to encourage roleplay by creating narrative requirements.
This makes it really easy to understand the "why does my character have access to these new things?" question that can often arise when progressing characters mechanically.
endif::[]

There are also focus paths, which represent your character growing and changing in play.
Focus paths have mechanical and narrative requirements in order for you to access them.
For example, the Occultist focus path requires you to have witnessed or studied an occult ritual.
The Cleric focus path requires you to have witnessed an act of chaos which causes you to devote your life and faith to a god.
The Necromancer focus path requires you to have found the Tome of Skulls and studied it in the dead of night for several nights.
There are many more focus paths, but they all give you access to a pool of moves in various tiers and skill unique to the focus path.

A focus path almost always has a way of it being lost, called [term]#losing focus#.
When you meet the conditions to [term]#lose focus# on a focus path, you immediately lose the focus path and all of the moves and other benefits of the path.
You gain XP equal to half of the XP cost of the focus path divided by 2, rounding up.

ifdef::showcommentary[]
.Regarding losing focus paths
[NOTE]
Focus paths being able to be lost is a narrative enforcement, but also a gamey mechanic.
Narratively, it makes sense for the paladin path to be lost when you forsake your oath.
Mechanically, maybe you _really_ need XP and you don't feel like being a paladin makes sense for you anymore.
The player can decide they want the XP and narratively make their character forsake their oath.
The other players all get to enjoy a story of how a paladin has literally fell from grace and while the paladin player gets to enjoy the XP they wanted.
Perhaps they really just wanted access to the Anti Paladin focus path which requires losing the paladin focus path?
endif::[]

=== Dungeoneer

*Cost* 10XP.

*Requirements* You have done at least 3 of the following in a single dungeon delve:

* Went inside without hesitation.
* Obtained a magical artefact inside.
* Killed a deadly beast that lurked there.
* Discovered the dark secrets of the dungeon.
* Disarmed or otherwise rendered useless past a deadly trap.
* Revealed and went through a hidden passageway.

.Dungeoneer Tier I Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Dungeoneer Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Dungeoneer Tier III Talents
* *Talent name* - Description

=== Beserker

*Cost* 15XP.

*Requirements*

.Beserker Tier I Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Beserker Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Beserker Tier III Talents
* *Talent name* - Description

=== Anti Paladin

*Cost* 15XP.

*Requirements* You have forsaken your paladin oath and broken ties with the organization that once honored you paladin title.

.Anti Paladin Tier I Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Anti Paladin Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Anti Paladin Tier III Talents
* *Talent name* - Description

=== Paladin

*Cost* 15XP.

*Requirements* You have went to a place that honors holiness or some other form of servitude, went through the rituals to become its champion, and swore your oath.

.Paladin Tier I Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Paladin Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Paladin Tier III Talents
* *Talent name* - Description

=== Cleric

*Cost* 15XP.

*Requirements*

.Cleric Tier I Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Cleric Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Cleric Tier III Talents
* *Talent name* - Description

=== Blood Mage

*Cost* 15XP.

*Requirements* Mystic core path.

.Blood Mage Tier I Talents
* *Blood infusion* - You can deal &times;HD damage to yourself to gain [term]#+HD magick power#.
* *Talent name* - Description
* *Talent name* - Description

.Blood Mage Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Blood Mage Tier III Talents
* *Talent name* - Description

=== Necromancer

*Cost* 15XP.

*Requirements*

.Occultist Tier I Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Occultist Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Occultist Tier III Talents
* *Talent name* - Description

=== Occultist

*Cost* 15XP.

*Requirements*

.Occultist Tier I Talents
* *Talent name* - Description
* *Talent name* - Description
* *Talent name* - Description

.Occultist Tier II Talents
* *Talent name* - Description
* *Talent name* - Description

.Occultist Tier III Talents
* *Talent name* - Description

== Careers

Your careers represent what you were before you decided to become an adventurer.
They provide one unique [term]#secondary ability#, some starting [term]#coin#, and starting [term]#equipment#.

* *If you are a young adult*, roll once on the careers table.
* *If you are middle-aged*, roll twice. Only keep one skill, but take all coin and gear you want.
* *If you are old*, roll three times. Only keep one skill, but take all coin and gear you want.

.Careers Table
[cols="1,99"]
|===
|d66|Job title and starting gear

|11
|*Acolyte* candlestick, censer, incense, 1D coin.

|12
|*Career title* stuff

|13
|*Career title* stuff

|14
|*Career title* stuff

|15
|*Career title* stuff

|16
|*Career title* stuff

|21
|*Career title* stuff

|22
|*Career title* stuff

|23
|*Career title* stuff

|24
|*Career title* stuff

|25
|*Career title* stuff

|26
|*Career title* stuff

|31
|*Career title* stuff

|32
|*Career title* stuff

|33
|*Career title* stuff

|34
|*Career title* stuff

|35
|*Career title* stuff

|36
|*Career title* stuff

|41
|*Career title* stuff

|42
|*Career title* stuff

|43
|*Career title* stuff

|44
|*Career title* stuff

|45
|*Career title* stuff

|46
|*Career title* stuff

|51
|*Career title* stuff

|52
|*Career title* stuff

|53
|*Career title* stuff

|54
|*Career title* stuff

|55
|*Career title* stuff

|56
|*Career title* stuff

|61
|*Career title* stuff

|62
|*Career title* stuff

|63
|*Career title* stuff

|64
|*Career title* stuff

|65
|*Career title* stuff

|66
|*Career title* stuff
|===

== Equipment

Equipment costs money when buying it from merchants and traders.
The cost of equipment is described in [term]#coin# (Also notated as c).

=== Slots

You start with 10 + [term]#force# slots for equipment.
When you have 500c, it takes up one slot.
500 more takes up another slot, and so on.

=== Tags

[horizontal]
Armor _Value_::
  Reduces damage to you by the value.
  [term]#Armor-piercing (AP)# can ignore up to the value.
  Only the armor with the highest value counts.
Blast:: Deals damage to a target and everyone adjacent to it.
Bulwark _Value_:: Armor with this tag can be used as an armor with this value without counting against its uses.
Bunch _Value_::
  You can have up to this [term]#quantity# of items with this trait and only take up 1 slot.
  If you wish to carry more of an item with this trait, it must occupy another slot.
Heavy::
  You can only carry up to your [term]#force# in items with this tag.
Two-Handed:: What it says on the tin. Requires two hands to wield.
Uses _Value_::
  You can use this item an amount of times equal to its value.
  It cannot be used further once you have used it that many times until it is repaired by an appropriate source.
  The better the source, the more uses you gain back.
Quantity _Value_::
  After a scene in which you used something with quantity, make a <<_fortune_roll,[term]#fortune roll +quantity#>>.
  *On a Miss*, reduce the quantity by 1.
  When the quantity reaches zero, it is spent and is removed from your inventory.

=== Weapons

* *Arrows* - _Quantity 1_, _Bunch 3_ *Cost* 5c.
* *Small Weapon* - (Dagger, short sword, small hammer, etc) *Cost* 5c *Damage* 1D.
* *Medium Weapon* - (Sword, spear, flail, etc) *Cost* 10c *Damage* 1D+1.
* *Heavy Weapon* - (Greatsword, glaive, battle axe, etc) _Two-Handed_, _Heavy_ *Cost* 25c *Damage* 1D+2.
* *Sling* - *Cost* 5c *Damage* d3.
* *Quiver* - *Cost* 10c. Holds arrows (up to _Quantity 3_).

=== Armor

All worn armor has an [term]#armor# value.
You can [term]#use# your armor to reduce damage by the armor value, but after doing so you mark a [term]#use# on your armor.

Shields add a bonus value to the [term]#armor# value set by your worn armor.
If you wield a shield without any worn armor, then treat the shield value as your armor value.

[term]#Armor piercing (AP)# ignores [term]#armor# value.

Armor can be repaired completely by visiting an armorsmith.
Mundane armor can be partially repaired with the proper tools and know-how by the PCs, [term]#taking action# trying to repair the armor, with the risk of rendering the armor completely unrepairable.

.Shields
* *Buckler* - _Uses 3_ *Cost* 5c *Armor Bonus* +1 *Damage* 1D.
* *Light Shield* - _Uses 6_, _Heavy_ *Cost* 10c *Armor Bonus* +1 *Damage* 1D.
* *Heavy Shield* - _Uses 6_, _Bulwark 1_, _Heavy_ *Cost* 10c *Armor Bonus* +2 *Damage* 1D+1.

.Worn Armor
* *Leather Armor* - _Uses 3_, _Armor 1_ *Cost* 30c.
* *Mail Armor* - _Uses 3_, _Heavy_, _Armor 2_ *Cost* 60c.
* *Splint Armor* - _Uses 5_, _Bulwark 1_, _Heavy_, _Armor 3_ *Cost* 90c.
* *Plate Armor* - _Uses 8_, _Bulwark 2_, _Heavy_, _Armor 3_ *Cost* 120c.

=== Adventuring Gear

[horizontal]
* *Chalk* - *Cost* 1c.
* *Whetstone* - *Cost* 1c.
* *Bandage* - *Cost* 2c. Heals 1HP.
* *Crowbar* - _Two-Handed_ *Cost* 5c *Damage* 1D.
* *Shovel* - _Two-Handed_ *Cost* 5c *Damage* 1D.
* *Tent, Personal* - *Cost* 10c.
* *Tent, Fits 3* - *Cost* 30c.
* *Waterskin* - *Cost* 2c.
* *Bedroll* - *Cost* 3c.
* *Grappling hook* - *Cost* 8c.

=== Animals

* *Riding Horse* Slots 5, *Cost* 80c.
* *Donkey* Slots 2, *Cost* 50c.

=== Vehicles

Vehicles have [term]#slots# that can be used to store equipment.

* *Cart* - *Slots* 15, *Cost* 30c.
* *Rowboat* - *Slots* 15, *Cost* 50c.
* *Wagon* - *Slots* 30, *Cost* 100c.
* *Stagecoach* - *Slots* 40, *Cost* 300c.
* *Sailing ship* - *Slots* 100, *Cost* 5000c.
* *Galleon* - *Slots* 300, *Cost* 10,000c.

=== Services

* *Poor inn* - *Cost* 6c/week.
* *Modest inn* - *Cost* 12c/week.
* *Comfortable inn* - *Cost* 24c/week.
* *Unskilled labor* - *Cost* 10c/week.
* *Professional labor* - *Cost* 30c/month.
* *Armed escort/passage*
** *Safe route* - *Cost* 6c/guard/day.
** *Dangerous route* - *Cost* 12c/guard/day.
** *Perilous route* - *Cost* 24c/guard/day.
* *Common murder* - *Cost* 5c.
* *Professional murder/assassination* - *Cost* 200c.
* *Prayers* - *Cost* 1c/month.
* *Repairs* - *Cost* 1/4th of the base cost for mundane items.

=== Housing

Living spaces have [term]#slots# that can be used to store equipment.

* *Hovel* - *Slots* 100 *Cost* 20c.
* *Small cottage* - *Slots* 200 *Cost* 250c.
* *House* - *Slots* 500 *Cost* 5,000c.
* *Mansion* - *Slots* 1000 *Cost* 20,000c.
* *Keep* - *Slots* 2000 *Cost* 150,000c.
* *Castle* - *Slots* 5000 *Cost* 600,000c.
* *Grand castle* - *Slots* 20,000 *Cost* 1,000,000c.

== Alchemy

== Mysticism

== Exposure to Chaos

== Monsters and Foes

Every monster has moves that describe its behavior and abilities.
Just like the normal consequences, they're things that you do when there's a lull in the action or when the PCs give you a golden opportunity.

Each monster has an instinct that describe its goals at a high level.
Some monsters live for conquest, or treasure, or simply for blood.
The monster's instinct is the guide to how to use it in the fiction.

The monster's description is where all its other features come from.
The description is how you know what the monster really is, the other elements just reflect the description.

Moves dictate how much [term]#damage# the monster can inflict at once.
A monster deals its damage to another monster or a PC whenever it causes them physical harm.
Some moves are special, like ones that can only be triggered by a critical failure, or a progress track being completed.

Each monster has tags that describe how it deals damage, including the range(s) of its abilities.
When trying to attack something out of its range (too close or too far) the monster's out of luck, no damage.
Any tag that can go on a weapon (like messy or slow) can also go on a monster.

There are special tags that apply only to monsters.
These tags, listed below, describe the key attributes of the monster -- qualities that describe how big they are and how, if at all, they organize themselves.

A monster's HP is a measure of how much damage it can take before it dies.
At 0 HP it's dead or out of action, unless otherwise stated.

Some monsters have progress tracks associated with them.
Each track is different and have different effects, such as a timer until a special ability goes off.
Sometimes it can represent a temporary vulnerability, like a troll when it is attacked by fire.

Some monsters are lucky enough to enjoy armor.
It's just like player armor: when a monster with armor takes damage it can mark a use of the armor to negate it.

Special qualities describe innate aspects of the monster that are important to play.
These are a guide to the fiction, and therefore the moves.
A quality like intangible means just what it says: mundane stuff just passes through it.
That means swinging a mundane sword at it will have extremely little [term]#reward#, and damage isn't a possibility for a start.

=== Tags

.Basic Tags
[horizontal]
Amorphous:: Its anatomy and organs are bizarre and unnatural.
Cautious:: It prizes survival over aggression.
Construct:: It was made, not born
Devious:: Its main danger lies beyond the simple clash of battle.
Hoarder:: It almost certainly has treasure.
Intelligent::
  It's smart enough that some individuals pick up other skills.
  The GM can adapt the monster by adding tags to reflect specific training, like a mage or warrior.
Magical:: It is by nature magical through and through.
Organized::
  It has a group structure that aids it in survival.
  Defeating one may cause the wrath of others. One may sound an alarm.
Planar:: It's from beyond this world
Stealthy:: It can avoid detection and prefers to attack with the element of surprise.
Terrifying:: Its presence and appearance evoke fear.

.Organization Tags
[horizontal]
Horde:: Where there's one, there's more. A lot more.
Group:: Usually seen in small numbers, 3–6 or so.
Solitary:: It lives and fights alone.

.Size Tags
[horizontal]
Tiny:: It's much smaller than a human child.
Small:: It's about the size of a human child.
Large:: It's much bigger than a human, about as big as a cart.
Huge:: It's as big as a small house or larger

=== Running Encounters

Here's some advice on running encounters.

You'll notice that monsters in {doctitle} don't have rules on _when_ they deal their damage.
That's because it's really up to the tone of game you want to play.
You can take the approach that whenever a player must [term]#suffer the consequences# that they'll be dealt damage -- that's fine.
The game you will get from that is a _very_ deadly one, though, as the resolution mechanic is weighted towards [term]#weak hits#, which will mean lots of damage will be flying around.

It's can be a good idea to use <<_soft_moves,[term]#soft moves#>> at first during a actions scenes when consequences are being suffered, and afterwards move towards using <<_hard_moves,[term]#hard moves#>>.

=== Sample Monster

.The Thing in the Well
[monster]
--
*HP* 16 *Armor* 1 ||
_Solitary_, _Large_, _Stealthy_

.Hard Moves
* *Dark Tentacles* - 
  *Damage* W[2D]+3.
  _Reach_, _Near_.

.Soft Moves
* Politely collect tribute
* Leverage townspeople through secrets
* Purify water
* Hide in darkened waters

*Instinct:* To devour

https://codex.dungeon-world.com/monster/82058[The Thing in the Well] created by https://codex.dungeon-world.com/profile/82057[Esoteric], licensed CC-BY.
--

[appendix]
== Bestiary

=== Dragons

==== The Tyranical Dragon of Flame

==== The Elder Dragon

==== The Blood Dragon

==== The Necrotic Dragon

=== Animals

==== Rats

=== Animals, Ferocious

==== Dire Animals

==== Bear

==== Wolf

=== Demons

=== Eldritch Horrors

==== Occulug

==== Shoggoth

=== Fae

=== Hilltribe Foes

==== Bugbears

==== Goblins

==== Giants

==== Hobgoblins

==== Orcs

==== Trolls

=== Golems

=== Mythical Creatures

=== Oozes

=== People, Mundane

.Bandit Lord
[monster]
--
Better to rule in hell than serve in heaven.

*HP* 12 *Armor* 1 ||
_Solitary_, _Intelligent_, _Organized_

.Hard Moves
* *Sharpened dagger* - 
  *Damage* B[2D]+2.
  _Close_.

.Soft Moves
* Make a demand
* Extort
* Topple power

*Instinct:* To lead
--

.Monster Name
[monster]
--
Description.

*HP* 1 *Armor* 1 ||
_Tag_

.Hard Moves
* *Attack Name* - 
  *Damage* DAMAGE.
  _Tag_.

.Soft Moves
* MOVE

*Instinct:* INSTINCT
--

=== People, Magical

=== Undead

==== Draugr

==== Ghouls

==== High Vampires

==== Liches

==== Skeletons

==== Vampire Spawn

==== Wraiths

==== Zombies

=== Spiders

=== Wyrms

.Wyvern
[monster]
--
6HP || _Flying_

.Attacks
* **Claws & Bite** Moderate Harm
* **Tail Whip** Minor Harm

.Consequences
* **Poisonous Barbs (miss)** Moderate poison 4. Resist +force.
--

.Kobold
[monster]
--
1HP

.Attacks
* **Spear or Dagger** Minor Harm

.Rewards
* **Cowardly** Another one flees after seeing their dead comrade.

.Consequences
* **Gang** Another creeps behind you or an ally with a dagger.
--

== Credits

The material and content of {doctitle} is licensed under the link:LICENSE-CC-BY-SA-4.0[Creative Commons Attribution-ShareAlike 4.0 International license].
The {repo-url}[source code of {doctitle}] is licensed under the link:LICENSE-AGPL[GNU Affero General Public license].

{doctitle} uses the work of https://www.bladesinthedark.com[Blades in the Dark] by John Harper, licensed for use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

{doctitle} uses the work of https://www.ironswornrpg.com[Ironsworn] by Shawn Tomkin, licensed for our use under the https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

{doctitle} uses the work of https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel, licensed for our use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

Spiked dragon head icon in the {doctitle} logo by https://delapouite.com/[Delapouite] under http://creativecommons.org/licenses/by/3.0/[CC BY 3.0].