////
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see https://www.gnu.org/licenses/.
////

= DragonHack
Sean-Patrick Ortencio Clayton
v1: PRE-ALPHA DRAFT
:doctype: book
:!showtitle:
:showcommentary:
:icons: font
:stylesheet: styles.css
:sectanchors:
:sectnums:
:sectnumlevels: 0
:version-label: Edition
:toc: right
:imagesdir: images
:favicon: images/dragonhack-logo.svg
:repo-url: https://github.com/sean-clayton/dragonhack

[#subtitle]
--
image::dragonhack-logotype.svg[Static,480,id=logo,align=center,alt=DragonHack,link=#]

[.text-center]
Basic
--

<<<

[preface]
== Preface

**Some acknowledgements:**

{doctitle} is inspired by several games.
Here is a non-exhaustive list in alphabetical order:

* https://www.bladesinthedark.com[Blades in the Dark] by John Harper.
* https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel.
* https://freeleaguepublishing.com/en/games/forbidden-lands/[Forbidden Lands] by the workers at Fria Ligan.
* https://www.ironswornrpg.com/[Ironsworn] by Shawn Tomkin.
* https://johnharper.itch.io/world-of-dungeons[World of Dungeons] by John Harper.
* ... and the many games derived from those.

If you enjoy {doctitle}, then be sure to check out these other games!

<<<

== The Basics

=== Playing {doctitle}

To play {doctitle}, you create your character, make some decisions about the world you inhabit, and set the story in motion.
When you encounter something dangerous or otherwise act by taking risks, your choices and the dice determine the outcome.

{doctitle} supports three modes of play.

Guided::
  One or more players take the role of their characters, the protagonists in your story, while a group mediator/gamemaster (GM) moderates the session.
  The GM helps bring the world to life, portrays the people and creatures you encounter, and makes decisions about the outcome of your actions.
Cooperative (Co-Op)::
  You and one or more friends play together to overcome challenges and complete quests.
  A GM is not required.
  The {doctitle} game system will help you explore the dramatic stories of your characters and their fateful vows.
Solo::
  As with cooperative play, no GM is necessary.
  You portray a lone heroic character in a dangerous world.
  Good luck!

[sidebar]
--
{doctitle} is primarily intended for small group play or solo.
One to four players (plus a GM in guided mode) is ideal.
The characters portrayed by other players are referred to in these rules as your allies.
--

==== What You Need to Play

{doctitle} requires some materials. Here is what you'll need:

* Two ten-sided dice (d10) for each player. These are [term]#challenge dice#.
* Two six-sided dice (d6) for each player. These are [term]#action dice#.
* Optionally, a set of percentile dice (d100) to use as [term]#oracle dice#.
* A printed character sheet for each player.

==== Mechanics and the Fiction

{doctitle} uses various mechanics, such as rolling dice and managing the stats and resources on your character sheet.
As a player, you will often make decisions based on a desired mechanical outcome.
For example, you might choose a particular action to get a bonus or advantage on your die roll.
The basic mechanics of {doctitle} are introduced in this chapter.

{doctitle} is also heavily reliant on the fiction, which is the imagined characters, situations, and places within your game.
You will play from the perspective of your character.
You will interpret actions and events in a way that is consistent with the dramatic, fictional reality you have forged for your story and your world.

==== Your Character

You use your character sheet to track your stats, gear, and overall condition.

However, your character is more than these mechanical bits.
You are a character in a rich story.
You have hopes and fears, virtues and failings.
You have a history.
You are, or were, part of a community.
This is the fiction of your character.
Consider a few of these details as you create your character, but don’t sweat it -- you’ll evolve it through play.
At the start of your game, put your character on stage to see what happens. 
Fill in the blanks -- for your character and your world -- as you go.

=== Rolling Dice

The core mechanic in {doctitle} is to [term]#take action#.
[term]#Taking action# is all about acting in the face of danger or some other kind of risk.

==== Risk

There are three levels of risk.

Minor Risk::
  Something bad could happen, but not very likely.
  Failure is not something to really worry about.
Moderate Risk::
  There's danger here if any failure were to occur.
Major Risk::
  If things go bad, they will go _very_ bad.
  Success here is absolutely paramount.

==== Reward

There are three levels of reward.

Minor Reward::
  You achieve something, but not nearly as much as you'd like.
  If you were stabbing something, it's technically stabbed, but not as much as you'd hope.
  If you were avoiding a danger, you technically avoid it, but you wish you did more.
Moderate Reward::
  You achieve a satisfactory outcome.
  If you were stabbing something, it's stabbed.
  If you were avoiding a danger, it was avoided.
Major Reward::
  You achieve much more than you had expected.
  If you were stabbing something, it sinks in like a hot knife through melted butter.
  If you were avoiding a danger, it is completely avoided, and probably is no longer dangerous for a time.

==== Taking Action

State what your goal is and the approach your character will take to make it happen.
You choose one relevent [term]#skill# to aid your approach.
The GM has the ultimate say if the skill is relevent, but should be biased towards your choice.
The GM will tell you the following:

* The [term]#attribute# you will use.
* The level of [term]#risk# the approach takes.
* The level of [term]#reward# given if the approach succeeds.
* Possible consequences if you fail and if you succeed.

You have [term]#advantage# if...

* An applicable effect (such as a magical item that provides [term]#advantage#) is increasing your character's abilities.
* Your character is being assisted by someone who has an appropriate skill or effect.

When you [term]#take action#, you roll multiple dice at once.

- **Challenge dice:** Two ten-sided dice (d10)
- **Action dice:**
  One six-sided dice (d6).
  If you have [term]#advantage#, re-roll the action die and take the highest.

Add the attribute value to your action die.
Add the skill value to your action die if you have one.
The total of your action die, your attribute, and any additional bonuses (such as a skill bonus) is your action score.

There are five possible results when rolling the dice to [term]#take action#:

[horizontal]
Critical Hit::
  Your action score is greater than all of the challenge dice.
  Both challenge dice are the same number.
Strong Hit::
  Your action score is greater than all of the challenge dice.
Weak Hit::
  Your action score is greater than only one of two challenge dice.
Miss::
  Your action score is not greater than any of the challenge dice.
Critical Miss::
  Your action score is not greater than any of the challenge dice.
  The challenge dice are the same number.

To determine the outcome of your action, compare the action score to each of the challenge dice.
You want it to be greater than the individual value of those dice.

.Take Action
[action]
--
[.lead]
When your character acts by taking a risk, state what your goal is and the approach your character will take to make it happen...

[horizontal]
[.risk]
Minor Risk::
+
[.lead]
You act on your terms. You exploit a dominant advantage.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
  [term]#Gain +3 momentum#.
* **Hit:**
  Things go as planned and all is well. A success.
  [term]#Gain +2 momentum#.
* **Weak Hit:**
  Your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
  [term]#Gain +1 momentum#.
* **Miss:**
  Your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.

Moderate Risk::
+
[.lead]
You go head to head. You act under fire. You take a chance.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
  [term]#Gain +1 momentum#.
* **Hit:**
  A success, and you realize what was at stake.
* **Weak Hit:**
  Overall a success, but you must [term]#suffer the consequences#.
* **Miss:**
  Things do not go your way.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences#.
* **Critical Miss:**
  Things do not go your way.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences#.

Major Risk::
+
[.lead]
You overreach your capabilities. You’re in serious trouble.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  A success, narrowly avoiding the consequences.
* **Weak Hit:**
  Technically a success, but there is a severe cost.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
* **Miss:**
  The worst outcome has happened.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
* **Critical Miss:**
  The worst outcome has happened, but somehow it got way worse.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
--

=== Momentum

Momentum is a special mechanic which is central to playing {doctitle}.
Your momentum value ranges from a 0 to 3 and represents how you are faring.

==== Gaining Momentum

You gain momentum primarily through [term]#taking action# and succeeding what you set out to accomplish.

Abilities, items, and other things can grant momentum as well.

==== Losing Momentum

Momentum is a resource that can be attacked when [term]#suffering the consequences#.
Some monsters can have abilities that let them reduce your momentum.
Some abilities give you the option of spending momentum in exchange for increased power.
The most common way to lose momentum is by [term]#spending momentum#.

==== Spending Momentum

[term]#Spending momentum# is a powerful option to use your built up successes to turn the tides when the action and drama is high.
When you have momentum, after you make an action roll, you may add your current momentum value to your action score to improve your result.
After you do this you go down to 0 momentum, and explain how you overcame and powered through the challenges.

You cannot gain momentum when spending momentum.

.Spending Momentum
[example]
--
Your momentum value is 3 and your action score is 4.
You roll a 5 and an 8 on your challenge dice.
A miss.
You may burn momentum to add your momentum value, 3, to the action score to make it 7.
This shifts your result from a miss to a weak hit.
You change your momentum from 3 to 0 and continue play.
--

==== Momentum Damage

Momentum can be damaged, resulting in a reduction of the maximum momentum you can have.
As you gain debilitaties or otherwise suffer other negative consequences, your momentum is damaged.
Almost always the reduction in momentum is tied to a negative effect on you, so if you lose the effect your maximum momentum will increase towards the original amount of 5.
The negative effect or whatever else that damages your momentum will say how much damage it does to it.
Often it is just 1 damage.

=== Progress Tracks

=== Harm

=== Exertion

==== Resistance and Armor

After seeing the roll result when [term]#taking action#, you can choose to [term]#resist# the consequences.
Take the following steps:

. If you are wielding, wearing, or otherwise protected by <<_armor,[term]#armor#>> that is effective against this kind of damage and the fiction allows for it, you can mark one wear off of the applicable armor and automatically succeed at resisting without any costs.
. Explain how your character or armor is resisting or reducing the severity of the consequences.
. If you haven't already succeeded at resisting at this step (by having some sort of armor), take the [term]#resist# action.
  The GM will tell you which [term]#attribute# you will use.

.Resist
[action]
--
[.lead]
When your character resists the consequences of their actions...

ifdef::showcommentary[]
.Regarding rolling resist...
[NOTE]
These could be done much better.
I don't know if I want every stat in play here.
Maybe as monsters are made and more kinds of damage are revealed in the game, they'll make this clearer to handle.
endif::[]

Roll [term]#+force# if resisting physical consequences through sheer might and endurance,
[term]#+edge# if resisting physical consequences through quickness or precision,
[term]#+heart# if resisting emotional damage,
// huehuehuehue
[term]#+mind# or [term]#+mystery#, whichever is higher, if resisting non-physical/non-emotional arkane/magick/occult consequences,
or [term]#+momentum# if resisting any other kind of harm.

[horizontal]
* **Critical Hit:**
  You do it with complete ease.
* **Hit:**
  The consequence is avoided.
* **Weak Hit:**
  The consequence is reduced.
  You can [term]#mark 1 exertion# to avoid it completely.
* **Miss:**
  The consequence still happens.
  You can [term]#mark 1 exertion# to avoid reduce it or [term]#mark 2 exertion# to avoid it completely.
--

===== Armor

If you have a type of [term]#armor# that applies to the situation, you can mark wear on the armor to reduce or avoid a consequence, instead of rolling to resist.

Each armor will have its own wear progress track.
When the progress track is filled, it is destroyed or otherwise rendered unusable.

Armor also states what kind of damage they can effectively resist against.
Using an armor to resist types of damage they are not effective against will result in greater wear or exertion costs.

.Leather Armor
[example]
--
Leather armors have 3 wear and typically can only resist against attacks of small weapons like daggers and shivs, but piercing attacks such as arrows can still penetrate them.
They can possibly protect against slashing attacks from larger weapons or from blunt force, but it will take more wear.
An attack like a shank from a dagger would only take one wear.
An attack like a sword slashing against them would require [term]#resisting# and spending 2 wear.
--

Armor can be repaired completely in the fiction by visiting an armorsmith or some other way of armor being repaired.
Mundane armor can be partially repaired with the proper tools and know-how by the PCs, [term]#taking action# trying to repair the armor.

==== Death

=== Paths

==== Warrior

==== Mystic

==== Scoundrel

=== Kin

==== Human

Human people.

==== Hobbitfolk

Small people.

==== Goblin

Small people with pointy ears.

==== Dwarf

Small people with beards.

==== Vyrmit

Mouse/rat/hamster people.

==== Kolussar

Ancient human/dwarf people.

==== Testadar

Turtle/tortoise people.

==== Kyrfit

Raven/crow/rook people.

=== Oracles

=== Equipment

=== The Flow of Play

== Your Character

=== Character Basics

==== Attributes

Each PC will start with an array of attribute points: 3, 2, 1, 1, 0.
Assign these points to any of the [term]#attributes# --
[term]#force#, [term]#edge#, [term]#mystery#, [term]#mind#, or [term]#heart#.

[horizontal]
Force:: Aggression, might, and intimidation.
Edge:: Haste, precision, and cunning.
Mystery:: Mysticism, arkane, and other magicks.
Mind:: Mental fortitude, intellect, and perception.
Heart:: Bravery, inpsiration, and understanding.

==== Skills

Skills are general abilities that increase your chances of succeeding when [term]#taking action#.
The following are the skills in {doctitle}:

* [term]#Accuracy#
* [term]#Care#
* [term]#Charm#
* [term]#Command#
* [term]#Discretion#
* [term]#Finesse#
* [term]#Focus#
* [term]#Frighten#
* [term]#Notice#
* [term]#Study#
* [term]#Wreck#
* [term]#Wrestle#

Your <<_paths,[term]#path#>> will provide 2 skills.
After applying the skills from your [term]#path#, choose 2 more skills.

==== Exertion

=== Debilities

==== Harm

==== Scars

=== Paths

=== Experience

=== Equipment

=== Character Creation Summary

[appendix]
== Foes and Encounters

Every monster has moves that describe its behavior and abilities.
Just like the normal consequences, they’re things that you do when there’s a lull in the action or when the PCs give you a golden opportunity.

Each monster has an instinct that describe its goals at a high level.
Some monsters live for conquest, or treasure, or simply for blood.
The monster’s instinct is the guide to how to use it in the fiction.

The monster’s description is where all its other features come from.
The description is how you know what the monster really is, the other elements just reflect the description.

Abilities dictate how much [term]#harm# the monster can inflict at once.
A monster deals its damage to another monster or a PC whenever it causes them physical harm.
Some abilities are special, like ones that can only be triggered by a critical failure, or a clock being completed.

Each monster has tags that describe how it deals damage, including the range(s) of its abilities.
When trying to attack something out of its range (too close or too far) the monster’s out of luck, no damage.
Any tag that can go on a weapon (like messy or slow) can also go on a monster.

There are special tags that apply only to monsters.
These tags, listed below, describe the key attributes of the monster -- qualities that describe how big they are and how, if at all, they organize themselves.

A monster’s HP is a measure of how much damage it can take before it dies.
At 0 HP it’s dead or out of action, unless otherwise stated.

Some monsters have progress tracks associated with them.
Each track is different and have different effects, such as a timer until a special ability goes off.
Sometimes it can represent a temporary vulnerability, like a troll when it is attacked by fire.

Some monsters are lucky enough to enjoy armor.
It’s just like player armor: when a monster with armor takes damage it can mark a use of the armor to negate it.

Special qualities describe innate aspects of the monster that are important to play.
These are a guide to the fiction, and therefore the moves.
A quality like intangible means just what it says: mundane stuff just passes through it.
That means swinging a mundane sword at it will have extremely little [term]#reward#, and damage isn't a possibility for a start.

=== Sample Monster

.Lich
[monster]
--
16 HP +
2 Armor (Magical) +
_Solitary_, _Magical_, _Intelligent_, _Cautious_, _Hoarder_, _Construct_

Motivation: To un-live

.Attacks
Magical Energy Blast::
  Moderate harm, ignores armor.
  _Near_, _Far_.
Blunt Staff::
  Minor harm.
  _Close_.
Magical Eruption □□□□::
  Severe harm, ignores armor, triggered by progress track completion.
  _Near_, _Far_.

.Special Abilities
* Cast a perfected spell of death or destruction
* Set a ritual or great working into motion
* Reveal a preparation or plan already completed
--


[appendix]
== Oracles

=== Using the Oracles

==== Oracles in Solo and Co-Op Play

==== Oracles in Guided Play

==== How to Use an Oracle

===== When Answers Lead to More Questions

===== Oracle Tables and Matches

=== Action Oracle

=== Theme Oracle

=== Combat Action Oracle

=== Exploration Oracle

////
== OLD STUFF BELOW

=== Creating a Character

Creating a character in {doctitle} is quite easy.
Here is a summary of the steps to make a new character:

. Assign <<_attributes,[term]#attribute points#>>.
. Choose a <<_paths,[term]#path#>> and apply its <<_skills,[term]#skill points#>>.
. Apply four more <<_skills,[term]#skill points#>>.
. Look at your <<_paths,[term]#path#>> and...
  * Answer all questions and make all choices.
  * Apply its <<_gear,[term]#gear#>>.
  * Determine your max <<_exhaustion_scars,[term]#exhaustion#>>.
. Choose a <<_kin,[term]#kin#>>.
. Set a <<_dark_desire,[term]#dark desire#>> and a <<_bonds,[term]#bond#>>.
. Choose more <<_gear,[term]#gear#>>.

=== Attributes

Each PC will start with an array of attribute points: 2, 1, 1.
Assign these points to any of the [term]#attributes# --
[term]#force#, [term]#edge#, [term]#mind#, or [term]#heart#.

[horizontal]
Force:: Aggression, might, and intimidation.
Edge:: Haste, precision, and cunning.
Mind:: Mental fortitude, intellect, and perception.
Heart:: Courage, diplomacy, and understanding.

=== Skills

Skills are general abilities that increase your chances of succeeding when [term]#taking action#.
The following are the skills in {doctitle}:

* [term]#Aim#
* [term]#Athletics#
* [term]#Care#
* [term]#Influence#
* [term]#Magick#
* [term]#Melee#
* [term]#Secrecy#
* [term]#Study#
* [term]#Survey#

Your [term]#path# will provide three points to skills, two of which goes into a single skill.
After applying the skills from your [term]#path#, add four more points into your skills.
Only one skill can have 2 points applied at the beginning of the game.
All other skills you choose can only have 1 point applied.

=== Exhaustion &amp; Scars

Exhaustion represents your character wearing down in dangerous situations.
For example, delving into dungeons or ancient ruins can always be a deadly venture.
While you are exploring these dark places, it can exhausting to always be tense, on the lookout, or being ready to act on a moment's notice.
It's exhaustion of the mind and body. Each character starts with 8 exhaustion.

=== Paths

=== Kin

Your kin 

=== Rolling the Dice

Only six-sided dice are used in {doctitle}.
In most rolls, you will be rolling multiple dice.
To make this easier to write, multiple dice rolled at once is noted as xd, where x is the number of dice rolled.
For example, a roll of a single die is written as 1d, and a roll of two dice is written as 2d.

When rolling dice in this manner, you are rolling a number of dice and only considering the highest result of the pool of dice you are rolling.

It is possible to roll 0d.
To do this, roll 2d, and then only consider the lowest of the two as your result.

Rolling dice when dealing damage often shows a + and a number next to a dice roll, and is noted as xd+y.
This means you roll x dice as normal and then add y to the result.
For example, 2d+4 means you roll 2d as described above, and then add 4 to the result.
If 2d results in a 3, then you add 4 which results in a final result of 7.

=== Risk

The core mechanic in {doctitle} is to [term]#take action#.
[term]#Taking action# is all about acting in the face of danger or some other kind of risk.

=== Taking Action

State what your goal is and the approach your character will take to make it happen.
You choose a relevent [term]#skill# to the approach.
The GM has the ultimate say in the skill, but should be biased towards your choice.
The GM will tell you the following:

* The [term]#attribute# you will use.
* The level of [term]#risk# the approach takes.
* The level of [term]#reward# given if the approach succeeds.
* Possible consequences if you fail and if you succeed.

You have [term]#advantage# if...

* An applicable effect (such as a magical item that provides [term]#advantage#) is increasing your character's abilities.
* Your character is being assisted by someone who has an appropriate skill or effect.

.Take Action
[action]
--
[.lead]
When your character acts by taking a risk...

- 1d for each point in the [term]#attribute#.
- 1d for each point in the relevent [term]#skill#.
- +1d if you have [term]#advantage#.

[horizontal]
[.risk]
Minor Risk::
+
[.lead]
You act on your terms. You exploit a dominant advantage.
+
* **Critical:**
  a success with [term]#increased reward#.
* **6:**
  things go as planned and all is well. A success.
* **4/5:**
  your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
* **1–3:**
  your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.

Moderate Risk::
+
[.lead]
You go head to head. You act under fire. You take a chance.
+
* **Critical:**
  a success with [term]#increased reward#.
* **6:**
  a success, and you realize what was at stake.
* **4/5:**
  overall a success, but you must [term]#suffer the consequences#.
* **1–3:**
  things do not go your way. [term]#Mark XP# and you must [term]#suffer the consequences#.

Major Risk::
+
[.lead]
You overreach your capabilities. You’re in serious trouble.
+
* **Critical:**
  a success with [term]#increased reward#.
* **6:**
  a success, narrowly avoiding the consequences.
* **4/5:**
  technically a success, but there is a severe cost.
  [term]#Mark XP# and you must [term]#suffer the consequences# accordingly.
* **1–3:**
  the worst outcome has happened.
  [term]#Mark XP# and you must [term]#suffer the consequences# accordingly.
--

=== Reward

Minor Reward::
You achieve something, but not nearly as much as you'd like.

Moderate Reward::
You achieve a moderate outcome.

Major Reward::
You achieve much more than you had expected.

.Dice Odds
[sidebar]
--
[cols="1,3,3,3,3",stripes=even]
|===
| Dice | Critical | Success | Partial | Fail

| 0 | 0% | 3% | 22% | 75%

| 1 | 0% | 17% | 33% | 50%

| 2 | 3% | 28% | 44% | 25%

| 3 | 7% | 35% | 45% | 13%

| 4 | 13% | 39% | 42% | 6%

| 5 | 20% | 40% | 37% | 3%

|===
--

=== Damage

If you are intending to do damage with a roll...

* **Critical:**
  You do 1 damage for every 6 rolled.
* **6:**
  You do 1 damage.
* **4/5:**
  The GM has discretion here, but typically you do 1 damage and [term]#suffer the consequences#.
* **1–3:**
  You do no damage and [term]#suffer the consequences#.

This is just the typical case with damage.
Feel free to change the damage depending on the [term]#reward# level of the approach.
The fiction should be consulted first when determining damage.

=== Double Down

After seeing the roll result when [term]#taking action#, you can choose to [term]#double down# and make an extra effort to succeed.
Take the following steps:

. Put all dice that show a 6 or a 1 to the side.
. Re-roll all remaining dice.
. For every dice that shows a 1, take a [term]#minor harm#.
. Consider this new roll your result and proceed with resolving [term]#take action#.

.Doubling Down
[example]
--
**Bob:** Alice, what do you do?

**Alice:** Alright, I want to slash at this troll while his back is to me!

**Bob:** Awesome, that'll be with Force, standard risk and you can finish him off if you succeed here. Otherwise, this thing will try to smash down on your companions.

**Alice:** Can't have that. Okay, three dice... <rolls>... 1, 3, and 4 -- failure it looks like.
Actually, no. I'm doubling down.
<re-rolls the 3 and 4>
A 2 and 6 -- a success!

**Bob:** Okay, awesome -- yeah, you're able to do it.
You still have that 1 though, so add a minor harm that says "leg cut" -- you swung your sword so hard to get the troll that you also swiped your leg just a bit.
--

=== Suffering Consequences

The GM chooses the consequences when the PCs [term]#suffer the consequences# while [term]#taking action#.
This is where the GM gets to shine -- these consequnces will provide the backbone of drama and action in {doctitle}.

* The most obvious outcome occurs.
* A success only in name -- they did not get _everything_ they wanted.
* The approach results in [term]#reduced reward#.
* Reveal a dark truth.
* Reveal a looming threat.
* Inflict a [term]#harm# or destroy [term]#gear#.
* The character succumbs to their [term]#dark desire#.
* Utilize your prep to modify the scene or situation.
* A _coup de grâce_ on a PC with an existing [term]#major harm# -- finish them off!

=== Harm &amp; Trauma

There are four levels of [term]#harm# in {doctitle}.
[term]#minor harm#, [term]#moderate harm#, [term]#major harm#, and [term]#fatal harm#.

[term]#Minor harm# represents smaller conditions and injuries such as a black eye, being dizzy, or being distracted.
Each PC can have up to three minor harm.
Minor harm [term]#reduces your effect# when [term]#taking action#.

[term]#Moderate harm# represents dangerous conditions such as a broken finger, 
Each PC can have up to two moderate harm.
Moderate harm reduces your dice pool by one when rolling dice.

[term]#Major harm# represents potentially deadly conditions such as a shattered leg, being impaled, being terrified, or losing control over your mind.
Each PC can only have one major harm.
Major harm takes a PC out of action almost always and they need immediate attention.
If a character has a major harm and the fiction allows for it, they are susceptible to a _coup de grâce_.

[term]#Fatal harm# represents an end to a PC, such as decapitation, their soul being ripped out and destroyed, or 
Each PC will die when gaining a fatal harm.
Fatal harm triggers the PC's <<_doomed,[term]#doomed#>> ability.
After completing their doomed ability, they die.

When you are taking a specific level of harm, but you already have the maximum allowed amount of harm for that level, you instead take a harm of the next highest tier.
For example, if a character already has three minor harm and has to mark another minor harm, they must mark a moderate harm if possible.

==== Doomed

When a PC suffers a fatal harm, they become doomed.
The doomed state represents when a character knows they will die,
but they get the final say in what happens.
Each [term]#path# states what happens and is possible when a PC becomes doomed.

=== Resisting Consequences

After seeing the roll result when [term]#taking action#, you can choose to [term]#resist# the consequences.
Take the following steps:

. If you have <<_armor,[term]#armor#>> and the fiction allows for it, you can mark one wear off of the applicable armor and automatically succeed at resisting.
. Explain how your character is resisting or reducing the severity of the consequences.
. If you haven't already succeeded at resisting, take the [term]#resist# action. The GM will tell you which [term]#attribute# you will use.

.Resist
[action]
--
[.lead]
When your character resists the consequences of their actions...

Roll 1d for each point in the [term]#attribute#.

[horizontal]
* **Critical:**
  You do it with complete ease.
* **6:**
  With a little effort you do it. [term]#Mark 1 exhaustion#.
* **4/5:**
  [term]#Mark 2 exhaustion#.
* **1–3:**
  You cut it close. [term]#Mark 3 exhaustion#.
--

=== Gathering Information

.Gather Information
[action]
--
Gather dice like you would [term]#taking action# and roll.


--

=== Advancement

== Characters

== Tags

== Monsters & Foes

== Spells & Sorcery

== Artifacts

== Running the Game
////

////
I use the phrase "GMs only" here so players are somewhat discouraged from
looking at this section and pointing to a section, saying
"this is how you're supposed to run it!"

The overall intent in this section is to help new GMs understand how this kind
of game *generally* runs. It is also meant to be a useful reference for
all GMs  to come here (during or even after session) and understanding
the game and how it runs.
////

////

This section is designed to be useful for GMs only.
Within you will find guidance, examples, and advice to assist you running a game of {doctitle}.

=== Asking for Rolls

Rolling dice in {doctitle} should happen _only_ when the action and drama call for it.
Constant dice-throwing can make a session take much longer than it should.
If there is no risk, then there shouldn't be any rolling.
It's much easier and quicker to just let the players succeed and move along.

In a deadly combat where you are outmatched or when traversing through a deadly dungeon is a perfect time and place to roll to find out what happens.
There's lots of risk in those situations, so let the rolls tell us what happens!

In other times, though, when there is no risk being taken, then don't ask for a roll.
Let the players succeed and move along until we get to a point where tension, action, and drama are back.

////

== Credits

The material and content of {doctitle} is licensed under the link:LICENSE-CC-BY-SA-4.0[Creative Commons Attribution-ShareAlike 4.0 International license].
The {repo-url}[source code of {doctitle}] is licensed under the link:LICENSE-AGPL[GNU Affero General Public license].

{doctitle} uses the work of https://www.bladesinthedark.com[Blades in the Dark] by John Harper, licensed for use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

{doctitle} uses the work of https://www.ironswornrpg.com[Ironsworn] by Shawn Tomkin, licensed for our use under the https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

{doctitle} uses the work of https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel, licensed for our use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

Spiked dragon head icon in the {doctitle} logo by https://delapouite.com/[Delapouite] under http://creativecommons.org/licenses/by/3.0/[CC BY 3.0].