= DragonHack
Sean-Patrick Ortencio Clayton
1st Edition PRE-ALPHA DRAFT
:doctype: book
:stylesheet: styles.css
:sectnums:
:sectnumlevels: 0
:!version-label:
:toc: right
:toclevels: 6

== Rules

=== Characters

=== Rolling the Dice

==== Risk

The core mechanic in {doctitle} is to [term]#take action#.

.Take Action
[action]
--
[.lead]
When your character acts by taking a risk...

State what your goal is and the approach your character will take to make it happen. The GM will tell you the following:

* The [term]#attribute# you will use.
* The level of [term]#risk# the approach takes.
* The level of [term]#reward# given if the approach succeeds.
* Possible consequences if you fail and if you succeed.

You have [term]#advantage# if your character has an appropriate skill related to this action, an effect is increasing your character's abilities, or is being assisted by someone who likewise has an appropriate skill or effect.

Roll the dice:

- 1d for each dot in the [term]#attribute#.
- +1d if you have [term]#advantage#.
- +1d if you accept a [term]#devil's bargain#.

'''

Low Risk::
+
[.lead]
You act on your terms. You exploit a dominant advantage.
+
* On a 12+,
  a success with [term]#increased reward#.
* On a 10+,
  things go as planned and all is well. A success.
* On a 7–9,
  your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
* On a 6-,
  your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.
Risky::
+
[.lead]
You go head to head. You act under fire. You take a chance.
+
* On a 12+,
  a success with [term]#increased reward#.
* On a 10+,
  a success, and you realize what was at stake.
* On a 7–9,
  overall a success, but you must [term]#suffer the consequences#.
* On a 6-,
  things do not go your way. [term]#Mark XP# and you must [term]#suffer the consequences#.
Great Risk::
+
[.lead]
You overreach your capabilities. You’re in serious trouble.
+
* On a 12+,
  a success with [term]#increased reward#.
* On a 10+,
  a success, narrowly avoiding the consequences.
* On a 7–9,
  technically a success, but there is a severe cost.
  [term]#Mark XP# and you must [term]#suffer the consequences# accordingly.
* On a 6-,
  the worst outcome has happened.
  [term]#Mark XP# and you must [term]#suffer the consequences# accordingly.
--

==== Reward

Low Reward::
+
You achieve something, but not nearly as much as you'd like.

Moderate Reward::
+
You achieve a moderate outcome.

Great Reward::
+
You achieve much more than you had expected.

==== Pushing Your Luck

.Push Your Luck
[action]
--
[.lead]
When you see the dice results of your action, but want to push your luck for a better result...

Re-roll any dice that is not a 6 or a 1, and then do the following in order:

. Add [term]#1 willpower# and re-calculate your roll result.
. On a 6-, choose which one does not happen:
  * Your character is hurt in their great effort.
    Suffer a [term]#harm#.
  * The opportunity has mostly been lost.
    The approach results in [term]#low reward#.
  * Your character ends up in a dangerous situation.
    [term]#Taking further action# in this scene, unless the situation drastically changes, will be a [term]#great risk#.
. Interpret the action again with the new results.
--

==== Suffering Consequences

.Suffering the Consequences
[action]
--
[.lead]
When your character suffers the consequences for an action, the GM chooses one. If the circumstances call for it, the GM chooses two:

* A success only in name -- they did not get _everything_ they wanted.
* The character spends [term]#2 willpower# and the approach succeeds without any further complications.
* The approach results in [term]#reduced reward#.
* Reveal a dark truth.
* Reveal a looming threat.
* Inflict a [term]#harm# or destroy [term]#gear#.
* Deal damage.
** ... and it's messy.
* The character's [term]#dark past# has caught up to them.
* Utilize your prep to modify the scene or situation.
--

== Credits

{doctitle} takes direct inspiration from https://johnharper.itch.io/world-of-dungeons[World of Dungeons], https://dungeon-world.com/[Dungeon World], and many hacks around built around those games -- to take what makes those games great and put a new spin on them.
{doctitle} also takes inspiration from https://freeleaguepublishing.com/en/games/forbidden-lands/[Forbidden Lands].

{doctitle} uses work from https://www.bladesinthedark.com[Blades in the Dark] by John Harper, licensed for use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

The material and content of {doctitle} is licensed under the https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International license].
The source code of this work is licensed under the https://www.gnu.org/licenses/agpl-3.0.en.html[GNU Affero General Public license].