////
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see https://www.gnu.org/licenses/.
////

= DragonHack
Sean-Patrick Ortencio Clayton
v1: PRE-ALPHA DRAFT
:doctype: book
:!showtitle:
:!table-caption:
:showcommentary:
:icons: font
:stylesheet: styles.css
:sectanchors:
:sectnums:
:sectnumlevels: 0
:version-label: Edition
:toc: right
:imagesdir: images
:favicon: images/dragonhack-logo.svg
:repo-url: https://github.com/sean-clayton/dragonhack

image::dragonhack-logotype.svg[Static,480,id=logo,alt=DragonHack,link=#]

<<<

[preface]
== Preface

{doctitle} is inspired by several games.
Here is a non-exhaustive list in alphabetical order:

* https://www.bladesinthedark.com[Blades in the Dark] by John Harper.
* https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel.
* https://freeleaguepublishing.com/en/games/forbidden-lands/[Forbidden Lands] by the workers at Fria Ligan.
* https://www.ironswornrpg.com/[Ironsworn] by Shawn Tomkin.
* The Streets of Marienburg.
* https://johnharper.itch.io/world-of-dungeons[World of Dungeons] by John Harper.
* ... and the many games derived from those.

If you enjoy {doctitle}, then be sure to check out these other games!

<<<

== Basic Rules

=== Playing {doctitle}

To play {doctitle}, you create your character, make some decisions about the world you inhabit, and set the story in motion.
When you encounter something dangerous or otherwise act by taking risks, your choices and the dice determine the outcome.

{doctitle} supports three modes of play.

Guided::
  One or more players take the role of their characters, the protagonists in your story, while a group mediator/gamemaster (GM) moderates the session.
  The GM helps bring the world to life, portrays the people and creatures you encounter, and makes decisions about the outcome of your actions.
Cooperative (Co-Op)::
  You and one or more friends play together to overcome challenges and complete quests.
  A GM is not required.
  The {doctitle} game system will help you explore the dramatic stories of your characters and their fateful vows.
Solo::
  As with cooperative play, no GM is necessary.
  You portray a lone heroic character in a dangerous world.
  Good luck!

[sidebar]
--
{doctitle} is primarily intended for small group play or solo.
One to four players (plus a GM in guided mode) is ideal.
--

==== What You Need to Play

{doctitle} requires some materials. Here is what you'll need:

* Several six-sided dice for each player.
  Three at the least, but more cannot hurt.
  These are used for [term]#action dice#, [term]#oracle dice#, and rolling things like [term]#damage#.
* A character sheet for each player.

==== Mechanics and the Fiction

{doctitle} uses various mechanics, such as rolling dice and managing the stats and resources on your character sheet.
As a player, you will often make decisions based on a desired mechanical outcome.
For example, you might choose a particular action to get a bonus or advantage on your die roll.
The basic mechanics of {doctitle} are introduced in this chapter.

{doctitle} is also heavily reliant on the fiction, which is the imagined characters, situations, and places within your game.
You will play from the perspective of your character.
You will interpret actions and events in a way that is consistent with the dramatic, fictional reality you have forged for your story and your world.

==== Your Character

You use your character sheet to track your stats, gear, and overall condition.

However, your character is more than these mechanical bits.
You are a character in a rich story.
You have hopes and fears, virtues and failings.
You have a history.
You are, or were, part of a community.
This is the fiction of your character.
Consider a few of these details as you create your character, but don't sweat it -- you'll evolve it through play.
At the start of your game, put your character on stage to see what happens. 
Fill in the blanks -- for your character and your world -- as you go.

=== Rolling Dice

The only dice used in {doctitle} are six-sided dice.

When we roll multiple dice, we shorten it to just the number of dice followed by a D, eg: Rolling two dice is 2D, and rolling 1 dice is 1D.

Sometimes you add or subtract a number to the total of the dice.
This has a + or - after the dice along with the number that is to be added or subtracted, respectively.
For example, if we want to add 1 to the total of a 2D roll, it looks like 2D+1.
If we want to subtract 1 from the total of a 2D roll, it looks like 2D-1.

Sometimes we want to roll multiple dice and not add them together, but take the best or worst of the dice rolled.
This is written as B[ ] or W[ ] with the number of dice in between the brackets.
For example, if we want to roll 2D and keep only the best of the two, it looks like B[2D].
If we want to roll 2D and keep only the worst of the two, it looks like W[2D].

We can also take multiple of the best or multiple of the worst.
This looks like the previous form, but with a number after the B or W, before the brackets.
For example, if we want to roll 3D and take the best two, it looks like B2[3D].
If we want to roll 3D and take the worst two, it looks like W2[3D].

And like rolling dice normally, we can still add a number to the total to these best of/worst of forms.
For example, B2[3D]+4 adds 4 to the total of the best two dice of the three rolled.
W2[3D]-1 subtracts 1 from the total of the worst two dice of the three rolled.

==== The Challenge Roll

The core mechanic in {doctitle} is the challenge roll.
To perform a challenge roll, you roll multiple dice at once:

- **Action dice:** Three dice (3D).

When making a challenge roll, you often with an attribute or other number, called a [term]#stat#.
For example, if you roll with the [term]#heart# attribute and its value is 3, this is written as "Roll [term]#+heart#" and you would add 3 to your action dice.

The total of your action dice, your stat, and any additional bonuses is your action score.

There are five possible results of a challenge roll:

[horizontal]
Critical Hit::
  Your action score is 13+ and at least two dice have the same value.
Strong Hit::
  Your action score is 13+.
Weak Hit::
  Your action score is 10/11/12.
Miss::
  Your action score is 9-.
Critical Miss::
  Your action score is 9- and at least two dice have the same value.

==== Surge Points

When you land a [term]#critical hit#, whatever number you rolled multiple times, multiply it by 2 and that's your [term]#surge points# for that action.

For example, if you roll your dice and get a 3, 3, and 3, that's only a 9, but after adding your modifier (let's say a +3), and a +1 from a skill, you got a 13 total action score.
You rolled multiple of the same number (3), so that makes it a critical hit.
The number you rolled multiple times is 3, so we multiply that by two to get the surge points available to you: 6.

You use surge points through abilities and features of your <<_paths,[term]#paths#>>.

Any surge points you do not use, you do not maintain.
Use them or lose them.

==== d66 and d666 Tables

Sometimes you'll see a d66 or d666 table.

*To roll d66*, roll a dice twice.
The first roll is the tens place and the second is the ones.

*To roll d666*, roll a dice three times.
The first roll is the hundreds place, the second is the tens, and the third is the ones.

==== GMs and the Dice

If you are playing as a GM, you can focus on guiding the game and responding to your player's questions and actions.
NPCs don't need to roll dice when they act, however, you might want some dice available for oracle rolls.

=== Taking Action

When a player character does something challenging, we [term]#take action# to see how it turns out.
An action is challenging if there's an obstacle to the PC's goal that's dangerous or troublesome in some way.
We don't make an action roll unless the PC is put to the test.
If their action is something that we'd expect them to simply accomplish, then we let them accomplish it without making any rolls.

==== Risk

There are three levels of risk.

Minor Risk::
  Something bad could happen, but not very likely.
  Failure is not something to really worry about.
Moderate Risk::
  There's danger here if any failure were to occur.
Major Risk::
  If things go bad, they will go _very_ bad.
  Success here is absolutely paramount.

==== Reward

There are three levels of reward.

Minor Reward::
  You achieve something, but not nearly as much as you'd like.
  If you were stabbing something, it's technically stabbed, but not as much as you'd hope.
  If you were avoiding a danger, you technically avoid it, but you wish you did more.
Moderate Reward::
  You achieve a satisfactory outcome.
  If you were stabbing something, it's stabbed.
  If you were avoiding a danger, it was avoided.
Major Reward::
  You achieve much more than you had expected.
  If you were stabbing something, it sinks in like a hot knife through melted butter.
  If you were avoiding a danger, it is completely avoided, and probably is no longer dangerous for a time.

State what your goal is and the approach your character will take to make it happen.
You choose the [term]#skill# you are using to act out your approach.
The GM will tell you the following:

* The [term]#attribute# you will use.
* The level of [term]#risk# the approach takes.
* The level of [term]#reward# given if the approach succeeds.
* Possible consequences if you fail and if you succeed.

.Take Action
[action]
--
[.lead]
When your character acts by taking a risk, state what your goal is and the approach your character will take to make it happen...

Roll [term]#+attribute#.

[horizontal]
[.risk]
Minor Risk::
+
[.lead]
You act on your terms. You exploit a dominant advantage.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  Things go as planned and all is well. A success.
* **Weak Hit:**
  Your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
* **Miss:**
  Your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.

Moderate Risk::
+
[.lead]
You go head to head. You act under fire. You take a chance.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  A success, and you realize what was at stake.
* **Weak Hit:**
  Overall a success, but you must [term]#suffer the consequences#.
* **Miss:**
  Things do not go your way.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences#.

Major Risk::
+
[.lead]
You overreach your capabilities. You're in serious trouble.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  A success, narrowly avoiding the consequences.
* **Weak Hit:**
  Technically a success, but there is a severe cost.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
* **Miss:**
  The worst outcome has happened.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
--

=== Fortune Roll

The fortune roll is a tool the GM can use to disclaim decision making.
You use a fortune roll in two different ways:

. **When you need to make a determination about a situation the PCs aren't directly involved in** and don't want to simply decide the outcome.
. **When an outcome is uncertain**, but no other roll applies to the situation at hand.

When you make a fortune roll you may assess [term]#any attribute or other stat# to determine the stat of the roll, and then perform a regular [term]#challenge roll#.

If no stat applies, roll [term]#+0# for sheer luck or roll [term]#+1–3# based on the situation at hand.

Sometimes you are forced to make a fortune roll.
This can be with a specific attribute or stat, or with a number added.
For example, making a fortune roll with heart, if its value is 3, it is written as "Roll [term]#fortune +heart#" and you would add 3 to the action die.
Making a fortune roll with +2 is written as "Roll [term]#fortune +2#" and you would add 2 to the action die.

.Fortune Roll
[action]
--
* **Critical Hit**: Exceptional result / Major, extreme reward.
* **Hit**: Good result / Moderate,  full reward.
* **Partial Hit**: Mixed result / Minor, partial reward.
* **Miss**: Bad result / Poor, little reward.
--

=== Surveying

.Surveying
[action]
--
When you search an area, ask questions, conduct an investigation, or follow a track, [term]#roll fortune +wits#.
If you act within a community or ask questions of a person with whom you share a bond, add +1.

* **Major**:
  You get exceptional details.
  The information is complete and follow-up questions may expand into related areas or reveal more than you hoped for.
* **Moderate**:
  You get good details.
  Clarifying and follow-up questions are possible.
* **Minor**:
  You get incomplete or partial information.
  More information gathering will be needed to get all the answers.
--

=== Exertion

==== Resistance and Armor

After seeing the roll result when [term]#taking action#, you can choose to [term]#resist# the consequences.
Take the following steps:

. If you are wielding, wearing, or otherwise protected by <<_armor,[term]#armor#>> that is effective against this kind of damage and the fiction allows for it, you can mark one wear off of the applicable armor and automatically succeed at resisting without any costs.
. Explain how your character or armor is resisting or reducing the severity of the consequences.
. If you haven't already succeeded at resisting at this step (by having some sort of armor), take the [term]#resist# action.
  The GM will tell you which [term]#attribute# you will use.

.Resist
[action]
--
[.lead]
When your character resists the consequences of their actions...

ifdef::showcommentary[]
.Regarding rolling resist...
[NOTE]
These could be done much better.
I don't know if I want every stat in play here.
Maybe as monsters are made and more kinds of damage are revealed in the game, they'll make this clearer to handle.
endif::[]

Roll [term]#+force# if resisting physical consequences through sheer might and endurance,
[term]#+edge# if resisting physical consequences through quickness or precision,
[term]#+shadow# if resisting detection or discovery through stealth or deception,
[term]#+heart# if resisting emotional damage,
[term]#+mind# or [term]#+mystery#, whichever is higher, if resisting non-physical/non-emotional arkane/magick/occult consequences,
or [term]#+0# if resisting any other kind of harm.

[horizontal]
* **Critical Hit:**
  You avoid all consequences with complete ease and end up in a 
* **Hit:**
  The consequence is avoided.
* **Weak Hit:**
  The consequence is reduced.
  You can [term]#mark 1 exertion# to avoid it completely.
* **Miss:**
  The consequence still happens.
  You can [term]#mark 1 exertion# to avoid reduce it or [term]#mark 2 exertion# to avoid it completely.
--

==== Death

When your character reaches 0HP, they die immediately.

=== Progress Tracks

A progress track is a multi-segment track.
Draw a progress track when you need to track ongoing effort against an obstacle or the approach of impending trouble.

Sneaking into the constables watch tower?
Make a progress track to track the alert level of the patrolling guards.
When the PCs suffer consequences from partial successes or missed rolls, fill in segments on the progress track until the alarm is raised.

Generally, the more complex the problem, the more segments in the progress track.

A complex obstacle is a 4-segment track.
A more complicated obstacle is a 6-segment track.
A daunting obstacle is an 8-segment track.

When you create a progress track, make it about the obstacle, not the method.
The progress tracks for an infiltration should be "`Interior Patrols`" and "`The Tower,`" not "`Sneak Past the Guards`" or "`Climb the Tower.`" The patrols and the tower are the obstacles -- the PCs can attempt to overcome them in a variety of ways.

Remember that a progress track tracks progress.
It reflects the fictional situation, so the group can gauge how they're doing.
A progress track is like a speedometer in a car.
It shows the speed of the vehicle -- it doesn't determine the speed.

==== Simple Obstacles

Not every situation and obstacle requires a progress track.
Use progress tracks when a situation is complex or layered and you need to track something over time -- otherwise, resolve the result of an action with a single roll.

Examples of progress tracks follow.

==== Danger Tracks

The GM can use a progress track to represent a progressive danger, like suspicion growing during a seduction, the proximity of pursuers in a chase, or the alert level of roaming monsters in a dungeon.
In this case, when a complication occurs, the GM ticks one, two, or three segments on the progress track, depending on the consequence level.
When the progress track is full, the danger comes to fruition -- the guards hunt down the intruders, activate an alarm, release the hounds, etc.

==== Racing Tracks

Create two opposed progress tracks to represent a race.
The PCs might have a progress track called "`Escape`" while the city watch have a progress track called "`Cornered.`" If the PCs finish their progress track before the watch fill theirs, they get away.
Otherwise, they're cornered and can't flee.
If both complete at the same time, the PCs escape to a safe location, but the watch are right outside!

You can also use racing progress tracks for an environmental hazard.
Maybe the PCs are trying to complete the "`Search`" progress track to find the lockbox on the sinking ship before the GM fills the "`Sunk`" progress track and the vessel goes down.

==== Linked Tracks

You can make a progress track that unlocks another progress track once it's filled.
For example, the GM might make a linked progress track called "`Trapped`" after an "`Alert`" progress track fills up.
As always, the method of action is up to the players and the details of the fiction at hand.

==== Mission Tracks

The GM can make a progress track for a time-sensitive mission, to represent the window of opportunity you have to complete it.
If the countdown runs out, the mission is scrubbed or changes -- the target escapes, the household wakes up for the day, etc.
Tug-of-war progress tracks

You can make a progress track that can be filled and emptied by events, to represent a back-and-forth situation.
You might make a "`Revolution!`" progress track that indicates when the refugees start to riot over poor treatment.
Some events will tick the progress track up and some will tick it down.
Once it fills, the revolution begins.
A tug-of-war progress track is also perfect for an ongoing turf war between two crews or factions.

==== Long-term Project

Some projects will take a long time.
A basic long-term project (like tinkering up a new feature for a device) is eight segments.
Truly long-term projects (like creating a new designer drug) can be two, three, or even four progress tracks, representing all the phases of development, testing, and final completion.
Add or subtract progress tracks depending on the details of the situation and complexity of the project.

A long-term project is a good catch-all for dealing with any unusual player goal, including things that circumvent or change elements of the mechanics or the setting.

==== Faction progress tracks

Each faction has a long-term goal.
When the PCs have downtime, the GM ticks forward the faction progress tracks that they're interested in.
In this way, the world around the PCs is dynamic and things happen that they're not directly connected to, changing the overall situation in the city and creating new opportunities and challenges.

The PCs may also directly affect NPC faction progress tracks, based on the missions and scores they pull off.
Discuss known faction projects that they might aid or interfere with, and also consider how a PC operation might affect the NPC progress tracks, whether the players intended it or not.

=== The Flow of Play

Like most roleplaying games, you play primarily from the perspective of your character.
What are you doing?
What are you trying to achieve?
What opposition and challenges do you face?
Your quests, and the characters and situations you encounter, will guide the fiction and the choices you make.

When you have questions about what you find, how other characters in your world respond, or what happens next, you can go with what feels right (if you're playing solo or co-op), or ask your GM.
When you are seeking inspiration or want to put it in the hands of fate, you want to consult an <<_oracles, oracle>>.
Use the yes/no questions and random prompts to generate interesting twists and new complications you might not have thought of on your own.
Above all, if it's interesting, dramatic and fits the fiction, make it happen.

If you are doing something covered by a move, refer to the move to resolve your action.
If it tells you to roll dice, do it.

Scoring a strong hit on a move means you are in control.
You're driving the narrative.
What do you do next?

A weak hit or a miss means you don't have control of the situation.
Instead of acting, you react.
What happens next?
If you're playing with a GM, they'll determine how the world responds.
Otherwise, you rely on your intuition and occasional oracle rolls to drive the narrative.

== Character Creation

=== Attributes

Each PC will start with an array of attribute points depending on their age.

* *Young Adult* 2, 2, 2, 1, 0, 0.
* *Middle-Aged/Old* 2, 1, 1, 1, 0, -1.

Assign these points to any of the [term]#attributes# --
[term]#force#, [term]#edge#, [term]#mystery#, [term]#mind#, or [term]#heart#.

[horizontal]
Force:: Aggression, might, and intimidation.
Edge:: Quickness, agility, and precision.
Shadow:: Sneakiness, deceptiveness, and cunning.
Mystery:: Mysticism, arkane, and other magicks.
Mind:: Mental fortitude, intellect, and perception.
Heart:: Bravery, inpsiration, and understanding.

Your age will modify these.
Different <<_kin,[term]#kin#>> have different age ranges for these age groups.

* *Young Adult:* No changes.
* *Middle-Aged:* +1 to [term]#heart#.
* *Old:* +1 to [term]#mind# and [term]#heart#, and -1 to [term]#force#.

Your <<_paths,[term]#core path#>> will increase an attribute by 1.
No attribute can exceed 3 at any point character creation.

=== Hit Points (HP) and Hit Dice (HD)

Every character starts with 6HP and 0HD.
[term]#Hit dice# provide a way of determining your vitality and also boost your HP.
Whenever you gain HD, roll the amount of HD gained in dice and add that to your current HP.
Whenever you re-roll your health, you roll a number of dice equal to your total HD, add 6, and that is your new health.
For example, if you have 2HD, you would roll 2D+6.

=== Skills

Skills are general abilities that increase your chances of succeeding when [term]#taking action#.
The following are the general skills in {doctitle}:

* [term]#Accuracy#
* [term]#Alchemicism#
* [term]#Awareness#
* [term]#Care#
* [term]#Charm#
* [term]#Command#
* [term]#Deception#
* [term]#Disarm Device#
* [term]#Finesse#
* [term]#Flexibility#
* [term]#Focus#
* [term]#Frighten#
* [term]#Leadership#
* [term]#Stealth#
* [term]#Study#
* [term]#Tactics#
* [term]#Treatment#
* [term]#Wreck#
* [term]#Wrestle#

Your <<_paths,[term]#paths#>> will provide skills -- these are your primary skills.
<<_focus_paths,[term]#Focus paths#>> provide primary skills not in the aforementioned list -- they provide skills unique to that focus path that you cannot obtain otherwise.
After determining your [term]#primary skills#, choose 2 more skills.
These 2 skills are your [term]#secondary skills#.

Skills, both primary and secondary, _always_ give a bonus to [term]#taking action#.
Primary skills, though, can provide greater bonuses than secondary skills.

=== Kin

==== Human

Human people.

.Age ranges
[horizontal]
Young Adult:: 16–25
Middle-Aged:: 26–59
Old:: 60+

==== Hobbitfolk

Small people.

.Age ranges
[horizontal]
Young Adult:: 20–29
Middle-Aged:: 30–69
Old:: 70+

==== Goblin

Small people with pointy ears.

.Age ranges
[horizontal]
Young Adult:: 11–15
Middle-Aged:: 16–29
Old:: 30+

==== Dwarf

Small people with beards.

.Age ranges
[horizontal]
Young Adult:: 25–100
Middle-Aged:: 101–199
Old:: 200+

==== Vyrmit

Mouse/rat/hamster people.

.Age ranges
[horizontal]
Young Adult:: 11–15
Middle-Aged:: 16–29
Old:: 30+

==== Kolussar

Ancient human/dwarf people.

.Age ranges
[horizontal]
Young Adult:: 40–119
Middle-Aged:: 120–249
Old:: 250+

==== Testadar

Turtle/tortoise people.

.Age ranges
[horizontal]
Young Adult:: 50–150
Middle-Aged:: 151–299
Old:: 300+

==== Kyrfit

Raven/crow/rook people.

.Age ranges
[horizontal]
Young Adult:: 14–20
Middle-Aged:: 21–34
Old:: 35+

=== Paths

There are two types of paths: core paths and focus paths.
Your core path is the primary path your character takes.
Focus paths are ways to shape your character into the concept you have in your mind.

Pick the core path for your character.
*If you are middle-aged*, pick a focus path for free and start with 5 to spend on abilities only.
*If you are old*, pick a focus path for free, one [term]#tier I ability#, and start with 5 to spend on abilities only.

Any XP you start with during character creation can only be spent during character creation.

==== Core Paths

ifdef::showcommentary[]
.Regarding core paths
[NOTE]
Core paths are the core chassis of a character.
They are essentially "classes" in other fantasy role-playing games.
endif::[]

There are three core paths: The warrior, the mystic, and the scoundrel.
The warrior knows their weapons and can kill many things with them.
The mystic knows mystery and spells and can kill many things with it.
The scoundrel has tricks, guile, and skulduggery and can kill many things through those.

===== The Warrior

Add +1 to [term]#force#.
It cannot exceed +3 at character creation.

Choose one of the three following features:

* *The Weaponmaster:*
* *The Beserker:*
* *The Oathtaker:*

===== The Mystic

Add +1 to [term]#mystery#.
It cannot exceed +3 at character creation.

Choose one of the three following features:

* *The Mage:*
* *The Blessed:*
* *The Oathtaker:*

===== The Scoundrel

Add +1 to [term]#shadow#.
It cannot exceed +3 at character creation.

Choose one of the three following features:

* *The Thief*
* *The Assassin*
* *The Oathtaker*

==== Focus Paths

ifdef::showcommentary[]
.Regarding focus paths
[NOTE]
Focus paths are the way to _really_ flesh out a character concept.
Focus paths are a _great_ place to add homebrew content.
These are like "subclasses" in other fantasy role-playing games.
The goal of a focus path is to encourage roleplay by creating narrative requirements.
This makes it really easy to understand the "why does my character have access to these new things?" question that can often arise when progressing characters mechanically.
endif::[]

There are also focus paths, which represent your character growing and changing in play.
Focus paths have mechanical and narrative requirements in order for you to access them.
For example, the Occultist focus path requires you to have witnessed or studied an occult ritual.
The Cleric focus path requires you to have witnessed an act of chaos which causes you to devote your life and faith to a god.
The Necromancer focus path requires you to have found the Tome of Skulls and studied it in the dead of night for several nights.
There are many more focus paths, but they all give you access to a pool of abilities in various tiers and skill unique to the focus path.

A focus path almost always has a way of it being lost, called [term]#losing focus#.
When you meet the conditions to [term]#lose focus# on a focus path, you immediately lose the focus path and all of the abilities and other benefits of the path.
You gain XP equal to half of the XP cost of the focus path divided by 2, rounding up.

ifdef::showcommentary[]
.Regarding losing focus paths
[NOTE]
Focus paths being able to be lost is a narrative enforcement, but also a gamey mechanic.
Narratively, it makes sense for the paladin path to be lost when you forsake your oath.
Mechanically, maybe you _really_ need XP and you don't feel like being a paladin makes sense for you anymore.
The player can decide they want the XP and narratively make their character forsake their oath.
The other players all get to enjoy a story of how a paladin has literally fell from grace and while the paladin player gets to enjoy the XP they wanted.
Perhaps they really just wanted access to the Anti Paladin focus path which requires losing the paladin focus path?
endif::[]

ifdef::showcommentary[]
.Regarding path power
[NOTE]
Paths are not meant to be a _huge_ power boost to characters.
Magic items are meant to be the biggest power boost a character can get -- they break all the rules and even rewrite them.
Paths are meant to be boosts, yes, but really they should increase versatility of a character.
For example, the Mystic path gets new properties for their spells they cast.
endif::[]

==== Abilities

Your paths give you access to abilities.
Abilities have two key things to note about them: Their [term]#tier# and their XP cost.
You can always access [term]#tier I# abilities as long as you spend their required XP cost.
To gain an ability in [term]#tier II# or above you must have N+2 abilities of the previous [term]#tier# where N is the number of abilities you already have in the [term]#tier# of the ability you are choosing.
For example, in order to gain your first [term]#tier II# ability, you must have two [term]#tier I# abilities.
In order to gain a second [term]#tier III# ability, you must have at least three [term]#tier II# abilities which means you must have at least four [term]#tier I# abilities.

=== Careers

Your careers represent what you were before you decided to become an adventurer.
They provide one unique [term]#secondary skill#, some starting [term]#coin#, and starting [term]#equipment#.

* *If you are a young adult*, roll once on the careers table.
* *If you are middle-aged*, roll twice. Only keep one skill, but take all coin and gear you want.
* *If you are old*, roll three times. Only keep one skill, but take all coin and gear you want.

.Careers Table
[cols="1,99"]
|===
|d66|Job title and starting gear

|11
|*Acolyte* candlestick, censer, incense, 1D coin.

|12
|*Career title* stuff

|13
|*Career title* stuff

|14
|*Career title* stuff

|15
|*Career title* stuff

|16
|*Career title* stuff

|21
|*Career title* stuff

|22
|*Career title* stuff

|23
|*Career title* stuff

|24
|*Career title* stuff

|25
|*Career title* stuff

|26
|*Career title* stuff

|31
|*Career title* stuff

|32
|*Career title* stuff

|33
|*Career title* stuff

|34
|*Career title* stuff

|35
|*Career title* stuff

|36
|*Career title* stuff

|41
|*Career title* stuff

|42
|*Career title* stuff

|43
|*Career title* stuff

|44
|*Career title* stuff

|45
|*Career title* stuff

|46
|*Career title* stuff

|51
|*Career title* stuff

|52
|*Career title* stuff

|53
|*Career title* stuff

|54
|*Career title* stuff

|55
|*Career title* stuff

|56
|*Career title* stuff

|61
|*Career title* stuff

|62
|*Career title* stuff

|63
|*Career title* stuff

|64
|*Career title* stuff

|65
|*Career title* stuff

|66
|*Career title* stuff
|===

==== Slots

You have with 10 + [term]#force# slots for equipment.
Items that have the [term]#bunch# trait take up only one slot as long as the [term]#quantity# does not exceed the bunch value.
Once it does, it increases slot usage by 1 and keeps on doing that when exceeding twice the bunch value, and so on.
Coins have a [term]#bunch# value of 500.

=== Character Creation Summary

== Experience

You gain experience by going through the items below _at the end of the session_ and determining if it applies to you.
Unless otherwise noted, each item only provides 1XP.

There are questions _everyone_ can get experience for:

* XP for showing up to the session.
* XP for killing a monster or otherwise dangerous creature.
** XP if it was was a mighty and deadly foe.
** XP if it was one of _the_ legendary dragons or otherwise a mighty, ancient, and deadly dragon.
* XP for obtaining treasure.
** XP if the total was worth 200C or more.
** XP if the total was worth 1000C or more.
* XP for obtaining a magical artefact.
* XP for discovering a new settlement, dangerous site, or ancient and storied location.
** XP for learning more about its dark or otherwise storied past.
** XP if it was a site full of danger (like a dungeon or enemy camp), and you went inside.
*** XP for going inside with _zero_ hesitation.
* XP for earning the trust of a new ally.
** XP if it was because you acted selflessly in their favor.
** XP for making _many_ new allies.
* XP for making a new enemy who swore to kill at least 1 member of your group.
** XP for making _many_ enemies.
** XP if they swore to kill just you.

Many <<_paths, [term]#paths#>> also provide ways of gaining XP.
Only characters with those paths can gain XP in those ways.
Some paths repeat items from the previous list of ways to gain XP.
This means you would get 1 more XP unless otherwise noted in the path.

== Equipment

Equipment costs money when buying it from merchants and traders.
The cost of equipment is described in [term]#coin# (Also notated as c).

=== Tags

[horizontal]
Armor _Value_::
  Reduces damage to you by the value.
  [term]#Armor-piercing (AP)# can ignore up to the value.
  Only the armor with the highest value counts.
Blast:: Deals damage to a target and everyone adjacent to it.
Bulwark _Value_:: Armor with this tag can be used as an armor with this value without counting against its uses.
Bunch _Value_::
  You can have up to this [term]#quantity# of items with this trait and only take up 1 slot.
  If you wish to carry more of an item with this trait, it must occupy another slot.
Heavy::
  You can only carry up to your [term]#force# in items with this tag.
Two-Handed:: What it says on the tin. Requires two hands to wield.
Uses _Value_::
  You can use this item an amount of times equal to its value.
  It cannot be used further once you have used it that many times until it is repaired by an appropriate source.
  The better the source, the more uses you gain back.
Quantity _Value_::
  After a scene in which you used something with quantity, make a <<_fortune_roll,[term]#fortune roll +quantity#>>.
  *On a Miss*, reduce the quantity by 1.
  When the quantity reaches zero, it is spent and is removed from your inventory.

=== Weapons

* *Arrows* - _Quantity 1_, _Bunch 3_ *Cost* 5c
* *Small Weapon* - (Dagger, short sword, small hammer, etc) *Cost* 5c *Damage* 1D
* *Medium Weapon* - (Sword, spear, flail, etc) *Cost* 10c *Damage* 1D+2
* *Heavy Weapon* - (Greatsword, glaive, battle axe, etc) _Two-Handed_, _Heavy_ *Cost* 25c *Damage* 1D+4
* *Sling* - *Cost* 5c *Damage* W[2D]

=== Armor

All worn armor has an [term]#armor# value.
You can [term]#use# your armor to reduce damage by the armor value, but after doing so you mark a [term]#use# on your armor.

Shields add a bonus value to the [term]#armor# value set by your worn armor.
If you wield a shield without any worn armor, then treat the shield value as your armor value.

[term]#Armor piercing (AP)# ignores [term]#armor# value.

Armor can be repaired completely by visiting an armorsmith.
Mundane armor can be partially repaired with the proper tools and know-how by the PCs, [term]#taking action# trying to repair the armor, with the risk of rendering the armor completely unrepairable.

Armor makes you slower.
Your total armor value, meaning including armor from a shield, changes how fast you are.

.Speed affected by armor
[horizontal]
1:: Barely slower to act.
2:: Slower to act.
3+:: Much slower to act.

.Shields
* *Buckler* - _Uses 3_ *Cost* 5c *Armor Bonus* +1 *Damage* 1D
* *Light Shield* - _Uses 6_, _Heavy_ *Cost* 10c *Armor Bonus* +1 *Damage* 1D
* *Heavy Shield* - _Uses 6_, _Bulwark 1_, _Heavy_ *Cost* 10c *Armor Bonus* +2 *Damage* 1D+1

.Worn Armor
* *Leather Armor* - _Uses 3_, _Armor 1_ *Cost* 30c
* *Mail Armor* - _Uses 3_, _Heavy_, _Armor 2_ *Cost* 60c
* *Splint Armor* - _Uses 5_, _Bulwark 1_, _Heavy_, _Armor 3_ *Cost* 90c
* *Plate Armor* - _Uses 8_, _Bulwark 2_, _Heavy_, _Armor 3_ *Cost* 120c

=== Adventuring Gear

[horizontal]
* *Chalk* - *Cost* 1c
* *Whetstone* - *Cost* 1c
* *Bandage* - *Cost* 2c. Heals 1HP.
* *Crowbar* - _Two-Handed_ *Cost* 5c *Damage* 1D
* *Shovel* - _Two-Handed_ *Cost* 5c *Damage* 1D
* *Tent, Personal* - *Cost* 10c
* *Tent, Fits 3* - *Cost* 50c

=== Transport

* *Cart and donkey* Slots 20, 50c

=== Services

* *Poor inn* - 6c/week
* *Modest inn* - 12c/week
* *Comfortable inn* - 24c/week
* *Unskilled labor* - 10c/week
* *Professional labor* - 30c/month
* *Armed escort*
  ** *Safe route* - 6c/guard/day
  ** *Dangerous route* - 12c/guard/day
  ** *Perilous route* - 24c/guard/day
* *Common murder* - 5c
* *Professional murder/assassination* - 200c
* *Prayers* - 1c/month
* *Repairs* - 1/4th of the base cost for mundane items.

=== Housing

== Alchemy

== Magick

== Exposure to Chaos

[appendix]
== Monsters and Foes

Every monster has moves that describe its behavior and abilities.
Just like the normal consequences, they're things that you do when there's a lull in the action or when the PCs give you a golden opportunity.

Each monster has an instinct that describe its goals at a high level.
Some monsters live for conquest, or treasure, or simply for blood.
The monster's instinct is the guide to how to use it in the fiction.

The monster's description is where all its other features come from.
The description is how you know what the monster really is, the other elements just reflect the description.

Abilities dictate how much [term]#harm# the monster can inflict at once.
A monster deals its damage to another monster or a PC whenever it causes them physical harm.
Some abilities are special, like ones that can only be triggered by a critical failure, or a progress track being completed.

Each monster has tags that describe how it deals damage, including the range(s) of its abilities.
When trying to attack something out of its range (too close or too far) the monster's out of luck, no damage.
Any tag that can go on a weapon (like messy or slow) can also go on a monster.

There are special tags that apply only to monsters.
These tags, listed below, describe the key attributes of the monster -- qualities that describe how big they are and how, if at all, they organize themselves.

A monster's HP is a measure of how much damage it can take before it dies.
At 0 HP it's dead or out of action, unless otherwise stated.

Some monsters have progress tracks associated with them.
Each track is different and have different effects, such as a timer until a special ability goes off.
Sometimes it can represent a temporary vulnerability, like a troll when it is attacked by fire.

Some monsters are lucky enough to enjoy armor.
It's just like player armor: when a monster with armor takes damage it can mark a use of the armor to negate it.

Special qualities describe innate aspects of the monster that are important to play.
These are a guide to the fiction, and therefore the moves.
A quality like intangible means just what it says: mundane stuff just passes through it.
That means swinging a mundane sword at it will have extremely little [term]#reward#, and damage isn't a possibility for a start.

=== Running Encounters

Here's some advice on running encounters.

You'll notice that monsters in {doctitle} don't have rules on _when_ they deal their damage.
That's because it's really up to the tone of game you want to play.
You can take the approach that whenever a player must [term]#suffer the consequences# that they'll be dealt damage -- that's fine.
The game you will get from that is a _very_ deadly one, though, as the resolution mechanic is weighted towards [term]#weak hits#, which will mean lots of damage will be flying around.

It's can be a good idea to use <<_soft_moves,[term]#soft moves#>> at first during a actions scenes when consequences are being suffered, and afterwards move towards using <<_hard_moves,[term]#hard moves#>>.

=== Sample Monster

.Lich
[monster]
--
*HP* 16 ||
*Magick Armor* ○○ ||
_Solitary_, _Magical_, _Intelligent_, _Cautious_, _Hoarder_, _Construct_

Motivation: To un-live

.Attacks
Magickal Energy Blast::
  Moderate harm.
  _Near_, _Far_.
Blunt Staff::
  Minor harm.
  _Close_.
Magickal Eruption ○○○○::
  Severe harm, ignores armor, triggered by progress track completion.
  _Close_, _Near_, _Far_.

.Special Abilities
* Cast a perfected spell of death or destruction
* Set a ritual or great working into motion
* Reveal a preparation or plan already completed
--

=== Dragons

==== The Tyranical Dragon of Flame

==== The Elder Dragon

==== The Blood Dragon

==== The Necrotic Dragon

=== Animals

==== Rats

=== Animals, Ferocious

==== Dire Animals

==== Bear

==== Wolf

=== Demons

=== Eldritch Horrors

==== Occulug

==== Shoggoth

=== Fae

=== Hilltribe Foes

==== Bugbears

==== Goblins

==== Giants

==== Hobgoblins

==== Orcs

==== Trolls

=== Golems

=== Mythical Creatures

=== Oozes

=== People, Mundane

=== People, Magical

=== Undead

==== Draugr

==== Ghouls

==== High Vampires

==== Liches

==== Skeletons

==== Vampire Spawn

==== Wraiths

==== Zombies

=== Spiders

=== Wyrms

.Wyvern
[monster]
--
6HP || _Flying_

.Attacks
* **Claws & Bite** Moderate Harm
* **Tail Whip** Minor Harm

.Consequences
* **Poisonous Barbs (miss)** Moderate poison 4. Resist +force.
--

.Kobold
[monster]
--
1HP

.Attacks
* **Spear or Dagger** Minor Harm

.Rewards
* **Cowardly** Another one flees after seeing their dead comrade.

.Consequences
* **Gang** Another creeps behind you or an ally with a dagger.
--

[appendix]
== Oracles

=== Using the Oracles

==== Oracles in Solo and Co-Op Play

==== Oracles in Guided Play

==== How to Use an Oracle

===== When Answers Lead to More Questions

===== Oracle Tables and Matches

=== Action Oracle

=== Theme Oracle

=== Combat Action Oracle

=== Exploration Oracle

[appendix]
== Hacking {doctitle}

[appendix]
== Expert Rules

=== The Adventuring Party

=== Modes of Play

==== Free Play

==== The Adventure

==== Downtime

== Credits

The material and content of {doctitle} is licensed under the link:LICENSE-CC-BY-SA-4.0[Creative Commons Attribution-ShareAlike 4.0 International license].
The {repo-url}[source code of {doctitle}] is licensed under the link:LICENSE-AGPL[GNU Affero General Public license].

{doctitle} uses the work of https://www.bladesinthedark.com[Blades in the Dark] by John Harper, licensed for use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

{doctitle} uses the work of https://www.ironswornrpg.com[Ironsworn] by Shawn Tomkin, licensed for our use under the https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

{doctitle} uses the work of https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel, licensed for our use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

Spiked dragon head icon in the {doctitle} logo by https://delapouite.com/[Delapouite] under http://creativecommons.org/licenses/by/3.0/[CC BY 3.0].