////
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see https://www.gnu.org/licenses/.
////

= DragonHack
Sean-Patrick Ortencio Clayton
1st Edition PRE-ALPHA DRAFT
:doctype: book
:!showtitle:
:stylesheet: styles.css
:sectnums:
:sectnumlevels: 0
:!version-label:
:toc: right
:toclevels: 6
:imagesdir: images
:favicon: images/dragonhack-logo.svg
:repo-url: https://github.com/sean-clayton/dragonhack

[#subtitle]
--
image::dragonhack-logotype.svg[Static,480,id=logo,align=center,alt=DragonHack]

[.text-center]
Basic
--

== Character Creation

Here are the steps to character creation in {doctitle}:

. Assign [term]#attribute points#.
. Choose a [term]#path# and its <<_skills,[term]#skill points#>>.
. Apply four more <<_skills,[term]#skill points#>>.
. Choose a [term]#kin#.
. Choose [term]#equipment#.

=== Attributes

Each PC will start with an array of attribute points: 2, 1, 1.
Assign these points to any of the [term]#attributes# --
[term]#force#, [term]#edge#, [term]#mind#, or [term]#heart#.

[horizontal]
Force:: Aggression, might, and intimidation.
Edge:: Haste, precision, and cunning.
Mind:: Mental fortitude, intellect, and perception.
Heart:: Courage, diplomacy, and understanding.

==== Luck

Luck is a special attribute.
Luck is almost never used as the attribute when [term]#taking action# during typical play.
It is instead primarily used to change the outcome of your roll when [term]#taking action#.

=== Skills

Skills are general abilities that increase your chances of succeeding when [term]#taking action#.
The following are the skills in {doctitle}:

* [term]#Aim#
* [term]#Analyze#
* [term]#Athletics#
* [term]#Care#
* [term]#Influence#
* [term]#Magick#
* [term]#Melee#
* [term]#Secrecy#

Your [term]#path# will provide three points to skills.
After applying the skills from your [term]#path#, add four more points into your skills.
No skill can exceed 2 points applied during character creation.

=== Exhaustion

Exhaustion represents your character wearing down in dangerous situations.
For example, delving into dungeons or ancient ruins can always be a deadly venture.
While you are exploring these dark places, it can exhausting to always be tense, on the lookout, or being ready to act on a moment's notice.
It's exhaustion of the mind and body.

=== Rolling the Dice

Only six-sided dice are used in {doctitle}.
In most rolls, you will be rolling multiple dice.
To make this easier to write, multiple dice rolled at once is noted as xd, where x is the number of dice rolled.
For example, a roll of a single die is written as 1d, and a roll of two dice is written as 2d.

When rolling dice in this manner, you are rolling a number of dice and only considering the highest result of the pool of dice you are rolling.

It is possible to roll 0d.
To do this, roll 2d, and then only consider the lowest of the two as your result.

Rolling dice when dealing damage often shows a + and a number next to a dice roll, and is noted as xd+y.
This means you roll x dice as normal and then add y to the result.
For example, 2d+4 means you roll 2d as described above, and then add 4 to the result.
If 2d results in a 3, then you add 4 which results in a final result of 7.

==== Risk

The core mechanic in {doctitle} is to [term]#take action#.
[term]#Taking action# is all about acting in the face of danger or some other kind of risk.

==== Taking Action

State what your goal is and the approach your character will take to make it happen.
You choose a relevent [term]#skill# to the approach.
The GM has the ultimate say in the skill, but should be biased towards your choice.
The GM will tell you the following:

* The [term]#attribute# you will use.
* The level of [term]#risk# the approach takes.
* The level of [term]#reward# given if the approach succeeds.
* Possible consequences if you fail and if you succeed.

You have [term]#advantage# if...

* An applicable effect (such as a magical item that provides [term]#advantage#) is increasing your character's abilities.
* Your character is being assisted by someone who has an appropriate skill or effect.

.Take Action
[action]
--
[.lead]
When your character acts by taking a risk...

- 1d for each point in the [term]#attribute#.
- 1d for each point in the relevent [term]#skill#.
- +1d if you have [term]#advantage#.
- +1d if you accept a [term]#devil's bargain#.

[horizontal]
[.risk]
Low Risk::
+
[.lead]
You act on your terms. You exploit a dominant advantage.
+
* **Critical:**
  a success with [term]#increased reward#.
* **6:**
  things go as planned and all is well. A success.
* **4/5:**
  your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
* **1–3:**
  your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.

Risky::
+
[.lead]
You go head to head. You act under fire. You take a chance.
+
* **Critical:**
  a success with [term]#increased reward#.
* **6:**
  a success, and you realize what was at stake.
* **4/5:**
  overall a success, but you must [term]#suffer the consequences#.
* **1–3:**
  things do not go your way. [term]#Mark XP# and you must [term]#suffer the consequences#.

Great Risk::
+
[.lead]
You overreach your capabilities. You’re in serious trouble.
+
* **Critical:**
  a success with [term]#increased reward#.
* **6:**
  a success, narrowly avoiding the consequences.
* **4/5:**
  technically a success, but there is a severe cost.
  [term]#Mark XP# and you must [term]#suffer the consequences# accordingly.
* **1–3:**
  the worst outcome has happened.
  [term]#Mark XP# and you must [term]#suffer the consequences# accordingly.
--

==== Reward

Low Reward::
You achieve something, but not nearly as much as you'd like.

Moderate Reward::
You achieve a moderate outcome.

Great Reward::
You achieve much more than you had expected.

==== Suffering Consequences

The GM chooses the consequences when the PCs [term]#suffer the consequences# while [term]#taking action#.
This is where the GM gets to shine -- these consequnces will provide the backbone of drama and action in {doctitle}.

* The most obvious outcome occurs.
* A success only in name -- they did not get _everything_ they wanted.
* The character spends [term]#2 willpower# and the approach succeeds without any further complications.
* The approach results in [term]#reduced reward#.
* Reveal a dark truth.
* Reveal a looming threat.
* Inflict a [term]#harm# or destroy [term]#gear#.
* Deal damage.
** _wip_ and it's messy.
* The character's [term]#dark past# has caught up to them.
* Utilize your prep to modify the scene or situation.

==== Push Yourself

==== Resisting Consequences

After seeing the roll result when [term]#taking action#, you can choose to [term]#resist# the consequences.
Take the following steps:

. If you have <<_armor,[term]#armor#>> and the fiction allows for it, you can mark one wear off of the applicable armor and automatically succeed at resisting.
. Explain how your character is resisting or reducing the severity of the consequences.
. If you haven't already succeeded at resisting, take the [term]#resist# action. The GM will tell you which [term]#attribute# you will use.

.Resist
[action]
--
[.lead]
When your character resists the consequences of their actions...

Roll 1d for each point in the [term]#attribute#.

[horizontal]
* **Critical:**
  You do it with complete ease.
* **6:**
  With a little effort you do it. [term]#Mark 1 exhaustion#.
* **4/5:**
  your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
* **1–3:**
  your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.
--

== GM Advice

=== Asking for Rolls

Rolling dice in {doctitle} should happen _only_ when the action and drama call for it.
Constant dice-throwing can make a session take much longer than it should.
If there is no risk, then there shouldn't be any rolling.
It's much easier and quicker to just let the players succeed and move along.

In a deadly combat where you are outmatched or when traversing through a deadly dungeon is a perfect time and place to roll to find out what happens.
There's lots of risk in those situations, so let the rolls tell us what happens!

In other times, though, when there is no risk being taken, then don't ask for a roll.
Let the players succeed and move along until we get to a point where tension, action, and drama are back.

== Credits

The material and content of {doctitle} is licensed under the link:LICENSE-CC-BY-SA-4.0[Creative Commons Attribution-ShareAlike 4.0 International license].
The {repo-url}[source code of {doctitle}] is licensed under the link:LICENSE-AGPL[GNU Affero General Public license].

{doctitle} takes direct inspiration from https://www.bladesinthedark.com[Blades in the Dark], https://johnharper.itch.io/world-of-dungeons[World of Dungeons], https://dungeon-world.com/[Dungeon World], and the many games derived from those.
{doctitle} also takes inspiration from https://www.ironswornrpg.com/[Ironsworn] and https://freeleaguepublishing.com/en/games/forbidden-lands/[Forbidden Lands].

{doctitle} uses work from https://www.bladesinthedark.com[Blades in the Dark] by John Harper, licensed for use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].

Spiked dragon head icon in the {doctitle} logo by https://delapouite.com/[Delapouite] under http://creativecommons.org/licenses/by/3.0/[CC BY 3.0].