:agpl: https://www.gnu.org/licenses/agpl-3.0.en.html
:cc-by-sa: https://creativecommons.org/licenses/by-sa/4.0/
:imagesdir: images

= DragonHack

image::dragonhack-logotype.svg[Static,480,align=center]

{doctitle} is a fantasy tabletop role-playing game where you delve in dungeons and destroy dragons.
It is made with the following goals:

* Easy to pick up and run very quickly.
* Able to play with modules and adventures made for other dragon-slaying, dungeon-delving fantasy systems with little work.
* A narrative-first game.
* A great system for a first-time role-playing game player, whether that's in the role of a game master or a player with a character.
* Easily ran in cooperative or solo modes with little-to-no outside supplements necessary.
* Easily able to adapt monsters and NPCs from material published for other similar games, but also easy to create your own from scratch.
* Player character death is not an extremely rare occurence.
* Easily hackable and open-source.

== COPYING

The _source code_ of this work is licensed under the {agpl}[AGPL v3] license.
If you take this source code and modify it to make your own game or product, you must also share your changes and license those changes under the {agpl}[AGPL v3] license.

The _mechanics and content_ of this work is licensed under the {cc-by-sa}[CC-BY-SA 4.0] license.
If you use mechanics or other content of this work to make your own game or product, you must also license it under the {cc-by-sa}[CC-BY-SA 4.0] license.

If you are taking the _source code_ and using it in something you are making, that falls under the {agpl}[AGPL v3] license stipulations.
If you are taking the _mechanics and content_ and using those in something you are making, that falls under the {cc-by-sa}[CC-BY-SA 4.0] license stipulations.

It is possible you take _both the source code and the mechanics and content_ for the same project.
The resulting code for such a project falls under {agpl}[AGPL v3] and the resulting mechanics and content fall under {cc-by-sa}[CC-BY-SA 4.0].

You can find link:LICENSE-AGPL[a copy of the AGPL v3 here].
You can find link:LICENSE-CC-BY-SA-4.0[a copy of the CC-BY-SA 4.0 license here].