////
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see https://www.gnu.org/licenses/.
////

= Sean's Fantasy Ruleset for Adventuring Games
Sean-Patrick Ortencio Clayton
v1: PRE-ALPHA DRAFT
:doctype: book
:!table-caption:
:showcommentary:
:icons: font
:stylesheet: styles.css
:sectanchors:
:version-label: Edition
:toc: right
:toclevels: 4
:imagesdir: images
:repo-url: https://github.com/sean-clayton/dragonhack

== Credits and Acknowledgements

The mechanics and content of this work is licensed under the link:LICENSE-CC-BY-SA-4.0[Creative Commons Attribution-ShareAlike 4.0 International license (CC-BY-SA)].

The source code of this work is licensed under the link:LICENSE-AGPL[GNU Affero General Public license (AGPL)].

This game includes material from the following works:

* https://www.bladesinthedark.com[Blades in the Dark] by John Harper, licensed for use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].
* https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel, licensed for our use under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license].
* https://www.ironswornrpg.com[Ironsworn] by Shawn Tomkin, licensed for our use under the https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].
* https://www.drivethrurpg.com/product/427272/Maze-World[Maze World] by Jasper Winters, licensed for our use under the https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International license].

'''

This game is inspired by _many_ other games.
Here is a non-exhaustive list in alphabetical order:

* https://www.bladesinthedark.com[Blades in the Dark] by John Harper.
* https://dungeon-world.com/[Dungeon World] by Sage LaTorra and Adam Koebel.
* https://freeleaguepublishing.com/en/games/forbidden-lands/[Forbidden Lands] by the workers at Fria Ligan.
* https://www.ironswornrpg.com/[Ironsworn] by Shawn Tomkin.
* https://www.drivethrurpg.com/product/250888/Knave[Knave] by Ben Milton.
* The Streets of Marienburg.
* https://johnharper.itch.io/world-of-dungeons[World of Dungeons] by John Harper.
* ... and the many games derived from those.

Please check out these other games!

== Rules

=== Player Principles

* Begin and end with the fiction.
* Play your character like a stolen car.
* Embrace challenge and failure.
* Celebrate success.
* Don't hog the spotlight, but shine when it's on you.

=== GM Principles

* Portray a dangerous world.
* Play to find out what happens.
* Do not over-prepare.
* Do not pull punches.
* Present problems without predetermined solutions.

=== Dealing Damage

.Dealing Damage
[move]
--
[.lead]
When you harm a foe but don't murder them outright...

Roll the applicable damage and say the result (plus any tags like messy, forceful, etc.).
The GM will reduce the victim's HP by that amount (less armor) and either describe the result or ask you to do so.
--

=== Rounding

Always round down when faced with non-integer numbers, unless otherwise noted.

=== The Challenge Roll

The core mechanic is the challenge roll.
To perform a challenge roll, you roll multiple dice at once and read the *single highest result*.

[sidebar]
If you ever need to roll zero or negative dice, roll 2D and take the lowest.
You cannot roll a critical hit when you have zero dice.

[horizontal]
Critical Hit::
  You roll *multiple 6s*.
Strong Hit::
  The highest die is a *6*.
Weak Hit::
  The highest die is a *4 or 5*.
Miss::
  The highest die is a *1, 2, or 3*.

There are three types of rolls that you'll use most often in the game:

Taking action::
  When a PC attempts an action that's dangerous or troublesome, you take an action to find out how it goes.
  Taking action and the resulting effects and consequences drive most of the game.
Fortune roll::
  The GM can make a fortune roll to disclaim decision making and leave something up to chance.
  How loyal is an NPC?
  How much does the plague spread?
  How much evidence is burned before the constables kick in the door?
Resistance roll::
  A player can make a resistance roll when their character suffers a consequence they don't like.
  The roll tells us how much stress their character suffers to reduce the severity of a consequence.

==== Hold

.Hold
[move]
--
[.lead]
When a move gives you [term]#"`hold X Currency`"#...

You can spend that currency as the move describes it.
--

==== Crits

.Surge
[move]
--
[.lead]
When you land a [term]#critical hit#...

[term]#Hold surge# in the amount of the number of dice with a 6 beyond the first.
You can spend [term]#surge# on [term]#surge moves#.

Any [term]#surge# you do not use immediately, you do not maintain.
--

==== GMs and the Dice

If you are playing as a GM, you can focus on guiding the game and responding to your player's questions and actions.
NPCs don't need to roll dice when they act, however, you might want some dice available for oracle rolls.

=== Taking Action

When a player character does something challenging, we [term]#take action# to see how it turns out.
An action is challenging if there's an obstacle to the PC's goal that's dangerous or troublesome in some way.
We don't make an action roll unless the PC is put to the test.
If their action is something that we'd expect them to simply accomplish, then we let them accomplish it without making any rolls.

==== Risk

There are three levels of risk.

Minor Risk::
  Something bad could happen, but not very likely.
  Failure is not something to really worry about.
Moderate Risk::
  There's danger here if any failure were to occur.
Major Risk::
  If things go bad, they will go _very_ bad.
  Success here is absolutely paramount.

==== Reward

There are three levels of reward.

Minor Reward::
  You achieve something, but not nearly as much as you'd like.
  If you were stabbing something, it's technically stabbed, but not as much as you'd hope.
  If you were avoiding a danger, you technically avoid it, but you wish you did more.
Moderate Reward::
  You achieve a satisfactory outcome.
  If you were stabbing something, it's stabbed.
  If you were avoiding a danger, it was avoided.
Major Reward::
  You achieve much more than you had expected.
  If you were stabbing something, it sinks in like a hot knife through melted butter.
  If you were avoiding a danger, it is completely avoided, and probably is no longer dangerous for a time.

State what your goal is and the approach your character will take to make it happen.
The GM will tell you the following:

* The [term]#approach# you will use.
* The level of [term]#risk# the approach takes.
* The level of [term]#reward# given if the approach succeeds.
* Possible consequences if you fail and rewards if you succeed.

.Take Action
[move]
--
[.lead]
When your character acts by taking a risk...

State what your goal is and the approach your character will take to make it happen.

* 1D for each point in the [term]#approaches# determined by the GM.
* +1D if you have [term]#advantage#.
* -1D if you have [term]#disadvantage#.

'''

[.risk]
Minor Risk::
+
[.lead]
You act on your terms. You exploit a dominant advantage.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  Things go as planned and all is well. A success.
* **Weak Hit:**
  Your character has a sudden realization that their approach will certainly succeed, but with a cost.
  They can try a different approach, or continue on and [term]#suffer the consequences#.
* **Miss:**
  Your character fails before any consequences occur, but a new [term]#risky# opportunity lies before them.
  They can attempt again with that approach or try something else.

Moderate Risk::
+
[.lead]
You take a chance. You act to defy danger.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
* **Hit:**
  A success, and you realize what was at stake.
* **Weak Hit:**
  Overall a success, but you must [term]#suffer the consequences#.
* **Miss:**
  Things do not go your way.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences#.

Major Risk::
+
[.lead]
You overreach your capabilities. You're in serious trouble.
+
* **Critical Hit:**
  A success with [term]#increased reward#.
  [term]#Gain +1 XP#.
* **Hit:**
  A success, narrowly avoiding the consequences.
  [term]#Gain +1 XP#.
* **Weak Hit:**
  Technically a success, but there is a severe cost.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
* **Miss:**
  The worst outcome has happened.
  [term]#Gain +1 XP# and you must [term]#suffer the consequences# accordingly.
--

=== Aid

.Aid
[move]
--
[.lead]
When you assist someone [term]#taking action#...

You give them [term]#advantage# to the roll, but you are succeptible to the consequences if there any.
--

=== Fortune Roll

The fortune roll is a tool the GM can use to disclaim decision making.
You use a fortune roll in two different ways:

. **When you need to make a determination about a situation the PCs aren't directly involved in** and don't want to simply decide the outcome.
. **When an outcome is uncertain**, but no other roll applies to the situation at hand.

When you make a fortune roll you may assess [term]#any attribute or other stat# to determine the stat of the roll, and then perform a regular [term]#challenge roll#.

If no stat applies, roll 1D for sheer luck or roll 1–3D based on the situation at hand.

Sometimes you are forced to make a fortune roll.
This can be with a specific attribute or stat, or with a number added.
For example, making a fortune roll with heart, if its value is 3, it is written as "Roll [term]#fortune +heart#" and you would roll 3 dice.

.Fortune Roll
[move]
--
* *1D* for each [term]#stat# rating.
* *+1D* for each [term]#major advantage#.
* *-1D* for each [term]#major disadvantage#.

'''

* **Critical Hit**: Exceptional result / Major. Great reward.
* **Hit**: Good result / Moderate. Full reward.
* **Partial Hit**: Mixed result / Minor. Partial reward.
* **Miss**: Bad result / Poor. Little or no reward.
--

=== Survey

.Survey
[move]
--
[.lead]
When you assess the situation, ask questions, conduct an investigation, or follow a track...

Roll [term]#fortune +insight#.

* **Major**:
  You get exceptional details.
  The information is complete and follow-up questions may expand into related areas or reveal more than you hoped for.
* **Moderate**:
  You get good details.
  Clarifying and follow-up questions are possible.
* **Minor**:
  You get incomplete or partial information.
  More information gathering will be needed to get all the answers.
--

=== Resistance

After seeing the roll result when [term]#taking action#, you can choose to [term]#resist# the consequences.
The GM will tell you which [term]#attribute# you will use.

.Resist
[move]
--
[.lead]
When your character resists the consequences of an action...

[term]#Mark 1 grit#.

The GM chooses which [term]#attribute# applies.
Roll 1D for each point in the [term]#attribute#.
Roll 1D for each point in your [term]#endure# action.

[horizontal]
* **Critical Hit:**
  You avoid all consequences and you are now in control of the situation.
  [term]#Gain 1 grit# back.
* **Hit:**
  The consequences are avoided.
* **Weak Hit:**
  The consequences are reduced.
  If taking damage, take half damage.
  You can [term]#mark 1 grit# to avoid them completely.
* **Miss:**
  The consequences still happen.
  You can [term]#mark 1 grit# to reduce them (half damage if taking damage) or [term]#mark 2 grit# to avoid them completely.
--

== Character Creation

. *Envision* your character and name them.
. Choose a <<_kin,[term]#kin#>>, determine your [term]#age#, and pick an [term]#origin# from your kin or <<_origins,roll an [term]#origin#>>.
  Determine your <<_attributes,[term]#attributes#>> according to your [term]#kin#.
. Set your <<_approaches,[term]#approaches#>> by distributing an array of points across [term]#aggression#, [term]#precision#, [term]#insight#, and [term]#heart#, as determined by your age.
  * *Young adult:* 2, 2, 1, 0.
  * *Middle-aged:* 2, 1, 1, 0.
  * *Old:* 2, 1, 0, 0.
  Each attribute can have up to 2 points allocated total.
  * *Young adult/middle-aged:* 3.
  * *Old:* 2.
. Distribute points across <<_actions,[term]#actions#>> as determined by your age.
  Each action can have up to 2 points allocated total.
  * *Young adult:* 6
  * *Middle-aged:* 10
  * *Old:* 12
. Set your max [term]#grit# to 5.
. Determine your <<_harm_damage_and_death,harm>> stats.
  * *Fatal* damage is 13+.
  * *Tier III* damage threshold is 9–12.
  * *Tier II* damage threshold is 5–8.
  * *Tier I* damage threshold is 1–4.
. Choose a <<_vices,[term]#vice#>>.
. Determine your <<_backgrounds,[term]#backgrounds#>>.
  * *Young adult:* Roll once on the backgrounds table.
  * *Middle-aged:* Pick twice on the backgrounds table.
  * *Old:* Pick three times on the backgrounds table.
. Purchase any additional equipment and determine your <<_speed,[term]#speed#>>.
  You begin with 10c in addition to all coin and equipment of your choice from your backgrounds. You also gain XP according to your age that you can spend now if you wish, or keep for later.
  * *Young adult:* 4XP.
  * *Middle-aged:* 12XP.
  * *Old:* 16XP.

== Experience

At the end of a session, have each person at the table go through the following items and, unless otherwise noted, mark 1XP for each one that everyone agrees is true for them.

* XP for showing up to the session.
* XP for someone in the group killing a monster or otherwise dangerous foe.
* XP for someone in the group looting a magical artefact.
* XP for someone in the group discovering a settlement, dangerous site, or otherwise storied.
* XP for someone in the group gaining the trust, gratitude, or other kind of allyship of an NPC.
* XP for someone in the group making a new enemy who will now be acting against you.
* XP for every 50 &times; [term]#grit# coin spent and wasted without any in-world gain on your <<_vices,[term]#vices#>> this session.
* XP for every <<_vices,[term]#vice#>> you succumbed to in a memorable way.

<<_paths, [term]#Paths#>> also provide ways of gaining XP.
Only characters with those paths can gain XP in those ways.

Additionally, you can change _one_ of these aspects of your character if the narrative supported it:

* Change one of your vices to a new one.
* Refund one talent completely and obtain a new one at the same cost.

== Approaches

[horizontal]
Aggression:: TBD
Precision:: TBD
Insight:: TBD
Heart:: TBD

== Actions

Attune::
  When you [term]#attune#, you .
Convince::
  When you [term]#convince#, you .
Clash::
  When you [term]#clash#, you .
Craft::
  When you [term]#craft#, you .
Decieve::
  When you [term]#decieve#, you .
Endure::
  When you [term]#endure#, you .
Perform::
  When you [term]#perform#, you .
Prowl::
  When you [term]#prowl#, you .
Reconnoiter::
  When you [term]#reconnoiter#, you .
Rush::
  When you [term]#rush#, you .
Shoot::
  When you [term]#shoot#, you .
Study::
  When you [term]#study#, you .
Tinker::
  When you [term]#tinker#, you .
Traverse::
  When you [term]#traverse#, you .
Trick::
  When you [term]#trick#, you .
Wreck::
  When you [term]#wreck#, you .

== Attributes

[horizontal]
Physique:: Your physical strength.
Willpower:: Your mental strength.

Your <<_kin,[term]#kin#>> determines these.

== Grit

Grit represents the amount of effort, physical or mental, you can exert while adventuring.
When you [term]#mark grit#, you add grit against your maximum grit.

You begin with 5 maximum grit.

When you are at max grit and you have to [term]#mark grit#, you're [term]#broken# and can no longer act.
This means you are either physically battered and unconscious, emotionally unavailable, mentally drained, or otherwise completely exhausted.

When you are broken you are out of any scene you currently are in and all scenes going forward, and are susceptible to a [term]#coup de grace#, which means all damage done to you is quadrupled.

You cannot perform a [term]#death move# if you are [term]#doomed# by a [term]#coup de grace#.

You are broken until you clear [term]#grit# through the [term]#come to# move or some other way.

=== Come To

.Come To
[move]
--
[.lead]
When you are at max grit, and you are still alive after w[2D] hours...

You clear [term]#1 grit#.
--

=== Increasing Max Grit

You can increase your max grit by spending XP.

== Harm, Damage, and Death

You suffer [term]#harm# when [term]#taking damage#.
When you take damage, you compare that to the damage thresholds of your harm.
The GM will tell you the type of harm you suffered.

* *Fatal* harm is 13+
* *Tier III* harm is 9–12.
* *Tier II* harm is 5–8.
* *Tier I* harm is 1–4.

The amount of harm you can take in each tier can change as you gain talents, but everyone starts with the following available boxes:

* *Fatal:* 0.
* *Tier III:* 1.
* *Tier II:* 2.
* *Tier I:* 2.

When you take action apply penalties to the roll as appropriate.

* *Tier III: Disabled* You must [term]#mark 2 grit# and be [term]#aided# to [term]#take action#.
* *Tier II: Disadvantage* You have [term]#disadvantage# on rolls to [term]#take action#.
* *Tier I: Lesser effect* Your actions are less effective.

If you have to take harm and there are no boxes available to fill, fill a box of a tier higher instead.
If you take harm and cannot mark a box, you are [term]#doomed#.

When your character becomes [term]#doomed#, and they do not make a [term]#death move#, they are most likely dead.

.Determine Your Fate
[move]
--
[.lead]
When your allies take a look at your body within a few hours of you becoming [term]#doomed#...

[term]#Roll a 2D fortune#.

* *On a critical hit*, you strongly gasp as they turn you over and you must explain to everyone how it wasn't as bad as it looked.
* *On a strong hit*, you are barely breathing and are in dire need of aid.
  Your grit is set to max.
* *On a weak hit*, you are alive just enough to say some last words.
* *On a miss*, you are dead.
--

== Kin

=== Human

Human people.

*Physique* 1.
*Willpower* 1.

.Origins
* *Civilized Society*
* *Wilds*
* *Tribal Society*

.Age ranges
[horizontal]
Young Adult:: 16–25
Middle-Aged:: 26–59
Old:: 60+

=== Hobbitfolk

Small people.

*Physique* 0.
*Willpower* 2.

.Origins
* *Civilized Society*

.Age ranges
[horizontal]
Young Adult:: 20–29
Middle-Aged:: 30–69
Old:: 70+

=== Dwarf

Small people with beards.

*Physique* 1.
*Willpower* 1.

.Origins
* *Civilized Society*
* *Mountain Society*

.Age ranges
[horizontal]
Young Adult:: 25–100
Middle-Aged:: 101–199
Old:: 200+

=== Goblin

Small people with pointy ears.

*Physique* 1.
*Willpower* 1.

.Origins
* *Civilized Society*
* *Wilds*
* *Tribal Society*

.Age ranges
[horizontal]
Young Adult:: 11–15
Middle-Aged:: 16–29
Old:: 30+

=== Ogre

Big goblin-like people.

*Physique* 2.
*Willpower* 0.

.Origins
* *Civilized Society*
* *Wilds*
* *Tribal Society*

.Age ranges
[horizontal]
Young Adult:: 40–119
Middle-Aged:: 120–249
Old:: 250+

== Origins

Your [term]#origin# is the starting point of your character's life.
Your [term]#kin# can determine your origin, but you can also roll on the table below to determine your origin no matter your kin.

.Origins
[cols="15,100"]
|===
|d66|Origin

|11–13|*Civilized Society*
|14–16|*Noxterra*
|21–23|*Mountain Society*
|24–26|*Tribal Society*
|31–33|*Wilds*
|34–36|Origin
|41–43|Origin
|44–46|Origin
|51–53|Origin
|54–56|Origin
|61–63|Origin
|64–66|Origin
|===

== Backgrounds

Your backgrounds represent what you were doing before you decided to become an adventurer.
They provide some starting [term]#coin#, [term]#equipment#, and a little detail on how your character has lived to this point.

* *If you are a young adult*, roll once on the background table according to your [term]#origin#.
* *If you are middle-aged*, pick twice on the background table according to your [term]#origin#.
* *If you are old*, pick three times on the background table according to your [term]#origin#.

.City Backgrounds
[cols="15,100"]
|===
|d66|Background

|11–13|*Background* Stuff.
|14–16|*Background* Stuff.
|21–23|*Background* Stuff.
|24–26|*Background* Stuff.
|31–33|*Background* Stuff.
|34–36|*Background* Stuff.
|41–43|*Background* Stuff.
|44–46|*Background* Stuff.
|51–53|*Background* Stuff.
|54–56|*Background* Stuff.
|61–63|*Background* Stuff.
|64|You moved to a farm. Pick or roll on the *Farmland Backgrounds*.
|65|*Background* Stuff.
|66|*Background* Stuff.
|===

.Farmland Backgrounds
[cols="15,100"]
|===
|d66|Background

|11–13|*Background* Stuff.
|14–16|*Background* Stuff.
|21–23|*Background* Stuff.
|24–26|*Background* Stuff.
|31–33|*Background* Stuff.
|34–36|*Background* Stuff.
|41–43|*Background* Stuff.
|44–46|*Background* Stuff.
|51–53|*Background* Stuff.
|54–56|*Background* Stuff.
|61–63|*Background* Stuff.
|64–66|*Background* Stuff.
|===

.Wilderness Backgrounds
[cols="15,100"]
|===
|d66|Background

|11–13|*Background* Stuff.
|14–16|*Background* Stuff.
|21–23|*Background* Stuff.
|24–26|*Background* Stuff.
|31–33|*Background* Stuff.
|34–36|*Background* Stuff.
|41–43|*Background* Stuff.
|44–46|*Background* Stuff.
|51–53|*Background* Stuff.
|54–56|*Background* Stuff.
|61–63|*Background* Stuff.
|64–66|*Background* Stuff.
|===

.Mountain Backgrounds
[cols="15,100"]
|===
|d66|Background

|11–13|*Background* Stuff.
|14–16|*Background* Stuff.
|21–23|*Background* Stuff.
|24–26|*Background* Stuff.
|31–33|*Background* Stuff.
|34–36|*Background* Stuff.
|41–43|*Background* Stuff.
|44–46|*Background* Stuff.
|51–53|*Background* Stuff.
|54–56|*Background* Stuff.
|61–63|*Background* Stuff.
|64–66|*Background* Stuff.
|===

.Hill Tribe Backgrounds
[cols="15,100"]
|===
|d66|Background

|11–13|*Background* Stuff.
|14–16|*Background* Stuff.
|21–23|*Background* Stuff.
|24–26|*Background* Stuff.
|31–33|*Background* Stuff.
|34–36|*Background* Stuff.
|41–43|*Background* Stuff.
|44–46|*Background* Stuff.
|51–53|*Background* Stuff.
|54–56|*Background* Stuff.
|61–63|*Background* Stuff.
|64–66|*Background* Stuff.
|===

.Outer Region Backgrounds
[cols="15,100"]
|===
|d66|Background

|11–13|*Background* Stuff.
|14–16|*Background* Stuff.
|21–23|*Background* Stuff.
|24–26|*Background* Stuff.
|31–33|*Background* Stuff.
|34–36|*Background* Stuff.
|41–43|*Background* Stuff.
|44–46|*Background* Stuff.
|51–53|*Background* Stuff.
|54–56|*Background* Stuff.
|61–63|*Background* Stuff.
|64–66|*Background* Stuff.
|===

== Vices

Vices are not limited to the ones below, but these are a popular list of vices many choose.

Drainage:: You seek the darkness and for no tomorrow.
Ego:: You seek to display opulence.
Gambling:: You seek thrills from chance.
Idealism:: You seek serving an unseen force.
Rebellion:: You seek to undermine authority.
Pleasure:: You seek escape and gratification through flesh, food, drugs, and art.
Unknown:: You seek the weird, foreign, taboo, and strange.

== Equipment

The [term]#cost# of equipment is described in coin (Shortened to just [term]#c#).

=== Slots

You start with 12 + [term]#physique# slots for equipment.

When you have 100c, it takes up one slot.
100 more takes up another slot, and so on.

=== Tags

[horizontal]
Applied:: Only useful when carefully applied to a person or object.
Armor _Value_::
  Reduces damage to you by the value.
  [term]#Piercing# ignores up to the value.
  Only the armor with the highest value counts.
+_Value_ Armor::
  Increases your total armor by the value.
Blast:: Deals damage to a target and everyone adjacent to it.
Awkward:: Unwieldy and difficult to use.
Bulwark _Value_:: Armor with this tag can be used as an armor with this value without counting against its uses.
Bunch _Value_::
  You can have up to this [term]#quantity# of items with this trait and only take up 1 slot.
  If you wish to carry more of an item with this trait, it must occupy another slot.
Close:: Can be used against something within arm's reach plus a foot or two.
Clumsy:: -1D ongoing to [term]#take action# while using this item.
Dangerous:: Easy to get in trouble with.
±_Value_ Effect::
  Modifies effectiveness according to the specified situation.
Far:: Can be used against something within shouting distance.
Forceful:: Can knock someone back a step or two--maybe even off their feet.
Hand:: Can be used against something only within arm's reach.
Heavy::
  You can only carry up to 2 + [term]#aggression# items with this tag.
Near:: Can be used against something that you can "see the whites of their eyes.".
Piercing _Value_:: Ignores _value_ of armor when dealing damage.
+_Value_ Piercing:: Increases [term]#piercing# by _value_ when dealing damage.
Messy:: When doing damage, it does so destructively--ripping flesh and things apart.
Reach:: Useful up to several feet awaywhen attacking--maybe as far as ten.
Reload:: After attacking, you must take more than a moment before you can attack again.
Slow:: Takes minutes or more to use.
Stun:: When doing damage, do stun damage instead of normal.
Thrown:: Can be easily thrown at something.
Two-Handed:: Requires two hands to wield.
Uses _Value_::
  You can use this item an amount of times equal to its value.
  It cannot be used further once you have used it that many times until it is repaired by an appropriate source.
  The better the source, the more uses you gain back.
Quantity _Value_::
  After a scene in which you used something with quantity, make a <<_fortune_roll,[term]#1D fortune roll#>>.
  *On a miss*, reduce the _value_ by 1.
  When the _value_ reaches zero, it is spent and is removed from your inventory.
  Every quantity still takes up slots as normal.

=== Weapons

* *Light Arrows* - *Cost* 5c. _Quantity 1_. *Damage* 3.
* *Heavy Arrows* - *Cost* 15c. *Damage* 4. _Quantity 1_, _Piercing 1_.
* *Small Weapon* (Dagger, short sword, small hammer, etc) - *Cost* 5c. *Damage* 3.
  _Hand_.
* *Medium Weapon* (Long sword, spear, flail, etc) - *Cost* 10c *Damage* 4.
  _Heavy_, _Hand_.
* *Heavy Weapon* (Greatsword, glaive, battle axe, etc) - *Cost* 25c *Damage* 5.
  _Two-Handed_, _Heavy_, _Reach_.
* *Sling* - *Cost* 5c. *Damage* 2.
* *Light Quiver* - *Cost* 10c. Holds light arrows (up to _Quantity 3_), and ignore their slots.
* *Heavy Quiver* - *Cost* 20c. Holds heavy arrows (up to _Quantity 2_), and ignore their slots.

=== Armor

Armor can be repaired completely by visiting an armorsmith.
Mundane armor can be partially repaired with the proper tools and know-how by the PCs, [term]#taking action# trying to repair the armor, with the risk of rendering the armor completely unrepairable.

.Shields
* *Buckler* - *Cost* 5c. *Damage* 2.
  _Uses 3_, _+1 Armor_, _Hand_.
* *Light Shield* - *Cost* 10c. *Damage* 2.
  _Uses 4_, _+1 Armor_, _Heavy_, _Hand_.
* *Heavy Shield* - *Cost* 30c *Damage* 3.
  _Uses 6_, _+2 Armor_, _Bulwark 1_, _Heavy_, _Hand_.

.Worn Armor
* *Leather Armor* - *Cost* 10c.
  _Uses 3_, _Armor 1_.
* *Mail Armor* - *Cost* 60c.
  _Uses 3_, _Armor 2_, _Heavy_.
* *Splint Armor* - *Cost* 90c.
  _Uses 4_, _Armor 3_, _Bulwark 1_, _Heavy_.
* *Plate Armor* - *Cost* 120c.
  _Uses 8_, _Armor 3_, _Bulwark 1_, _Heavy_.

=== Adventuring Gear

[horizontal]
* *Chalk* - *Cost* 1c.
* *Whetstone* - *Cost* 1c.
* *Bandage* - *Cost* 2c.
* *Crowbar* - *Cost* 5c *Damage* 1D.
  _Two-Handed_.
* *Shovel* - *Cost* 5c *Damage* 1D.
  _Two-Handed_.
* *Tent, Personal* - *Cost* 10c.
* *Tent, Fits 3* - *Cost* 30c.
* *Waterskin* - *Cost* 2c.
* *Bedroll* - *Cost* 3c.
* *Grappling hook* - *Cost* 8c.

=== Animals

* *Riding Horse* Slots 5, *Cost* 80c.
* *Donkey* Slots 2, *Cost* 50c.

=== Vehicles

Vehicles have [term]#slots# that can be used to store equipment.

* *Cart* - *Slots* 15, *Cost* 30c.
* *Rowboat* - *Slots* 15, *Cost* 50c.
* *Wagon* - *Slots* 30, *Cost* 100c.
* *Stagecoach* - *Slots* 40, *Cost* 300c.
* *Sailing ship* - *Slots* 100, *Cost* 5000c.
* *Galleon* - *Cost* 10,000c.

=== Services

* *Poor inn* - *Cost* 6c/week.
* *Modest inn* - *Cost* 12c/week.
* *Comfortable inn* - *Cost* 24c/week.
* *Unskilled labor* - *Cost* 10c/week.
* *Professional labor* - *Cost* 30c/month.
* *Armed escort/passage*
** *Safe route* - *Cost* 6c/guard/day.
** *Dangerous route* - *Cost* 12c/guard/day.
** *Perilous route* - *Cost* 24c/guard/day.
* *Common murder* - *Cost* 5c.
* *Professional murder/assassination* - *Cost* 200c.
* *Prayers* - *Cost* 1c/month.
* *Repairs* - *Cost* 1/4th of the base cost for mundane items.

=== Housing

Taxes and upkeep for housing in civilized areas are 10% base cost per month.
Upkeep for housing in non-civilized areas is 5% base cost per month.

* *Hovel* - *Cost* 20c.
* *Small cottage* - *Cost* 250c.
* *House* - *Cost* 5,000c.
* *Mansion* - *Cost* 20,000c.
* *Keep* - *Cost* 150,000c.
* *Castle* - *Cost* 600,000c.
* *Grand castle* - *Cost* 1,000,000c.

== Alchemy

== Magic

=== Mystweaving

=== Divine Magic

=== Ritual Magic

== Exposure to Chaos

== Calendar

There are 8 months in the year, with each month having 5 weeks, and each week containing 9 days, for a total of 360 days per year.

There are 24 hours in each day.
Each day is split into four

The year contains four seasons, beginning with summer and proceeding to autumn, winter, and then spring.
Each month represents the beginning and end of each of the four seasons.

.Months
. Sunsoar (Early Summer)
. Suncrest (Late Summer)
. Dewveil (Early Autumn)
. Shadeharvest (Late Autumn)
. Starwhisper (Early Winter)
. Frostgrain (Late Winter)
. Bloomgust (Early Spring)
. Dunewake (Late Spring)

.Weekdays
. Duunday
. Osiday
. Sharday
. Karday
. Stelday
. Kasday
. Wirlday
. Nirday
. Ansday

.Time of Day
* Morning
* Day
* Evening
* Night